do $$
begin
  if to_regclass('public.admin_audit_logs') is null and to_regclass('public.admin_audit_log') is not null then
    alter table public.admin_audit_log rename to admin_audit_logs;
  end if;
end $$;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id),
  action text not null,
  target_table text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_admin_created_at_idx
  on public.admin_audit_logs(admin_id, created_at desc);

create index if not exists admin_audit_logs_action_created_at_idx
  on public.admin_audit_logs(action, created_at desc);

create index if not exists admin_audit_logs_target_idx
  on public.admin_audit_logs(target_table, target_id);

alter table public.admin_audit_logs enable row level security;

drop policy if exists "admin_select_admin_audit_log" on public.admin_audit_logs;
drop policy if exists "admin_select_admin_audit_logs" on public.admin_audit_logs;
create policy "admin_select_admin_audit_logs"
on public.admin_audit_logs for select to authenticated
using (public.is_admin());

grant select on public.admin_audit_logs to authenticated;

comment on table public.admin_audit_logs is 'Registro de acciones sensibles ejecutadas desde el portal de administración.';
comment on column public.admin_audit_logs.action is 'Nombre estable de la acción ejecutada, por ejemplo admin.user.deactivate.';
comment on column public.admin_audit_logs.metadata is 'Datos no sensibles que ayudan a justificar y reconstruir la acción.';
