create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.teacher_digest_deliveries (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  period_start timestamptz not null,
  period_end timestamptz not null,
  frequency text not null check (frequency in ('daily', 'weekly')),
  timezone text not null default 'Europe/Madrid',
  recipient_email text not null,
  status text not null default 'pending' check (status in ('pending','processing','sent','retry','failed','cancelled','unsubscribed')),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 5 check (max_attempts between 1 and 10),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by uuid,
  sent_at timestamptz,
  provider_message_id text,
  last_error_code text,
  last_error_message text,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (teacher_id, frequency, period_start, period_end)
);
create index if not exists teacher_digest_due_idx on public.teacher_digest_deliveries(status, next_attempt_at);
create index if not exists teacher_digest_teacher_idx on public.teacher_digest_deliveries(teacher_id, created_at desc);
alter table public.teacher_digest_deliveries enable row level security;
revoke all on public.teacher_digest_deliveries from public, anon, authenticated;

alter table public.user_notification_preferences
  add column if not exists teacher_digest_last_sent_at timestamptz,
  add column if not exists teacher_digest_unsubscribed_at timestamptz;

create or replace function public.enqueue_due_teacher_digests(p_now timestamptz default now())
returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer := 0;
begin
  insert into public.teacher_digest_deliveries(
    teacher_id, period_start, period_end, frequency, timezone, recipient_email, snapshot
  )
  select
    p.id,
    case when np.teacher_digest_frequency='weekly'
      then date_trunc('week', p_now at time zone coalesce(up.timezone,'Europe/Madrid')) at time zone coalesce(up.timezone,'Europe/Madrid')
      else date_trunc('day', p_now at time zone coalesce(up.timezone,'Europe/Madrid')) at time zone coalesce(up.timezone,'Europe/Madrid') end,
    p_now,
    np.teacher_digest_frequency,
    coalesce(up.timezone,'Europe/Madrid'),
    coalesce(nullif(trim(np.teacher_reminder_email),''), au.email),
    jsonb_build_object(
      'inactive_students', case when np.teacher_inactive_student_alerts then (
        select count(distinct e.student_id)
        from public.subjects s join public.enrollments e on e.subject_id=s.id
        join public.profiles sp on sp.id=e.student_id
        where s.teacher_id=p.id and coalesce(s.is_archived,false)=false
          and coalesce(sp.active,true)=true
          and (sp.role_id <> 'guest' or coalesce(sp.expires_at, p_now + interval '1 day') > p_now)
          and not exists (select 1 from public.attempt_history ah where ah.student_id=e.student_id and ah.created_at >= p_now-interval '7 days')
      ) else 0 end,
      'open_reviews', case when np.teacher_open_review_alerts then (
        select count(*) from public.attempt_history ah
        join public.questions q on q.id=ah.question_id
        join public.subjects s on s.id=q.subject_id
        where s.teacher_id=p.id and ah.manual_review_status in ('pending','needs_changes','in_review')
      ) else 0 end,
      'sensitive_actions', case when np.teacher_sensitive_action_alerts then (
        select count(*) from public.teacher_audit_logs tal
        where tal.teacher_id=p.id and tal.created_at >= coalesce(np.teacher_digest_last_sent_at, p_now-interval '7 days')
          and (tal.action ilike '%delete%' or tal.action ilike '%archive%' or tal.action ilike '%password%' or tal.action ilike '%code%' or tal.action ilike '%remove%')
      ) else 0 end,
      'generated_at', p_now
    )
  from public.profiles p
  join auth.users au on au.id=p.id
  join public.user_notification_preferences np on np.user_id=p.id
  left join public.user_preferences up on up.user_id=p.id
  where p.role_id='teacher' and coalesce(p.active,true)
    and np.email_enabled=true
    and np.teacher_digest_frequency in ('daily','weekly')
    and np.teacher_digest_unsubscribed_at is null
    and coalesce(nullif(trim(np.teacher_reminder_email),''), au.email) is not null
    and (
      (np.teacher_digest_frequency='daily' and extract(hour from p_now at time zone coalesce(up.timezone,'Europe/Madrid'))=7
       and (np.teacher_digest_last_sent_at is null or np.teacher_digest_last_sent_at < p_now-interval '20 hours'))
      or
      (np.teacher_digest_frequency='weekly' and extract(isodow from p_now at time zone coalesce(up.timezone,'Europe/Madrid'))=1
       and extract(hour from p_now at time zone coalesce(up.timezone,'Europe/Madrid'))=7
       and (np.teacher_digest_last_sent_at is null or np.teacher_digest_last_sent_at < p_now-interval '6 days'))
    )
  on conflict do nothing;
  get diagnostics v_count = row_count;
  return v_count;
end $$;

create or replace function public.claim_teacher_digest_batch(p_worker_id uuid, p_limit integer default 25)
returns setof public.teacher_digest_deliveries language plpgsql security definer set search_path=public as $$
begin
  return query
  with due as (
    select id from public.teacher_digest_deliveries
    where status in ('pending','retry') and next_attempt_at<=now()
      and attempts<max_attempts
    order by next_attempt_at,id for update skip locked limit greatest(1,least(p_limit,100))
  ), updated as (
    update public.teacher_digest_deliveries d
    set status='processing', attempts=d.attempts+1, locked_at=now(), locked_by=p_worker_id, updated_at=now()
    from due where d.id=due.id returning d.*
  ) select * from updated;
end $$;

create or replace function public.finish_teacher_digest(
  p_id bigint, p_status text, p_provider_message_id text default null,
  p_error_code text default null, p_error_message text default null,
  p_retry_after_seconds integer default null
) returns void language plpgsql security definer set search_path=public as $$
declare v public.teacher_digest_deliveries%rowtype;
begin
  select * into v from public.teacher_digest_deliveries where id=p_id for update;
  if not found then raise exception 'Digest not found'; end if;
  if p_status not in ('sent','retry','failed','cancelled','unsubscribed') then raise exception 'Invalid digest status'; end if;
  update public.teacher_digest_deliveries set
    status=p_status, provider_message_id=coalesce(p_provider_message_id,provider_message_id),
    last_error_code=p_error_code, last_error_message=left(p_error_message,500),
    next_attempt_at=case when p_status='retry' then now()+make_interval(secs=>coalesce(p_retry_after_seconds,300)) else next_attempt_at end,
    sent_at=case when p_status='sent' then now() else sent_at end,
    locked_at=null, locked_by=null, updated_at=now()
  where id=p_id;
  if p_status='sent' then
    update public.user_notification_preferences set teacher_digest_last_sent_at=now(), updated_at=now() where user_id=v.teacher_id;
  elsif p_status='unsubscribed' then
    update public.user_notification_preferences set teacher_digest_unsubscribed_at=now(), teacher_digest_frequency='off', updated_at=now() where user_id=v.teacher_id;
  end if;
end $$;
revoke all on function public.enqueue_due_teacher_digests(timestamptz) from public,anon,authenticated;
revoke all on function public.claim_teacher_digest_batch(uuid,integer) from public,anon,authenticated;
revoke all on function public.finish_teacher_digest(bigint,text,text,text,text,integer) from public,anon,authenticated;
grant execute on function public.enqueue_due_teacher_digests(timestamptz) to service_role;
grant execute on function public.claim_teacher_digest_batch(uuid,integer) to service_role;
grant execute on function public.finish_teacher_digest(bigint,text,text,text,text,integer) to service_role;

create table if not exists public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id text not null,
  device_name text not null,
  platform text not null,
  user_agent text,
  ip_hash text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoked_by uuid references public.profiles(id) on delete set null,
  new_device_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,device_id)
);
create index if not exists user_sessions_user_idx on public.user_sessions(user_id,last_seen_at desc);
alter table public.user_sessions enable row level security;
create policy "users_read_own_sessions" on public.user_sessions for select to authenticated using (user_id=auth.uid());
revoke insert,update,delete on public.user_sessions from anon,authenticated;

create table if not exists public.account_backup_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  code_hash text not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists backup_codes_user_idx on public.account_backup_codes(user_id) where used_at is null;
alter table public.account_backup_codes enable row level security;
revoke all on public.account_backup_codes from public,anon,authenticated;

create or replace function public.register_user_session(p_device_id text,p_device_name text,p_platform text,p_user_agent text default null,p_ip_hash text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid(); v_id uuid; v_new boolean:=false; v_revoked timestamptz;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  select id,revoked_at into v_id,v_revoked from public.user_sessions where user_id=v_user and device_id=p_device_id;
  if v_id is null then
    v_new:=true;
    insert into public.user_sessions(user_id,device_id,device_name,platform,user_agent,ip_hash,new_device_notified_at)
    values(v_user,left(p_device_id,200),left(p_device_name,120),left(p_platform,30),left(p_user_agent,500),p_ip_hash,now()) returning id into v_id;
    perform public.create_notification(
      v_user, case when exists(select 1 from public.profiles where id=v_user and role_id='teacher') then 'teacher' else 'student' end,
      'announcement', 'Nuevo inicio de sesión',
      format('Se ha iniciado sesión desde %s (%s).',left(p_device_name,120),left(p_platform,30)),
      'shield-checkmark-outline', '#F6A64A', null, 'user_sessions', v_id::text,
      jsonb_build_object('session_id',v_id,'device_name',p_device_name,'platform',p_platform),
      'new-device:'||v_user::text||':'||left(p_device_id,200)
    );
  else
    update public.user_sessions set device_name=left(p_device_name,120),platform=left(p_platform,30),user_agent=left(p_user_agent,500),ip_hash=coalesce(p_ip_hash,ip_hash),last_seen_at=now(),updated_at=now() where id=v_id;
  end if;
  return jsonb_build_object('session_id',v_id,'is_new_device',v_new,'revoked',v_revoked is not null);
end $$;

create or replace function public.revoke_user_session(p_session_id uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.user_sessions set revoked_at=now(),revoked_by=auth.uid(),updated_at=now()
  where id=p_session_id and user_id=auth.uid();
  if not found then raise exception 'Session not found'; end if;
end $$;

create or replace function public.revoke_other_user_sessions(p_current_device_id text)
returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer;
begin
  update public.user_sessions set revoked_at=now(),revoked_by=auth.uid(),updated_at=now()
  where user_id=auth.uid() and device_id<>p_current_device_id and revoked_at is null;
  get diagnostics v_count=row_count; return v_count;
end $$;

grant execute on function public.register_user_session(text,text,text,text,text) to authenticated;
grant execute on function public.revoke_user_session(uuid) to authenticated;
grant execute on function public.revoke_other_user_sessions(text) to authenticated;

alter table public.profiles add column if not exists expires_at timestamptz;
alter table public.profiles add column if not exists converted_at timestamptz;
update public.profiles set expires_at=coalesce(expires_at,created_at+interval '30 days') where role_id='guest';
create index if not exists profiles_guest_expiry_idx on public.profiles(expires_at) where role_id='guest' and converted_at is null;

create or replace function public.prepare_guest_profile()
returns trigger language plpgsql set search_path=public as $$
begin
  if new.role_id='guest' and new.expires_at is null then new.expires_at:=now()+interval '30 days'; end if;
  if old.role_id='guest' and new.role_id='student' then new.converted_at:=now(); new.expires_at:=null; end if;
  return new;
end $$;
drop trigger if exists prepare_guest_profile_trigger on public.profiles;
create trigger prepare_guest_profile_trigger before insert or update on public.profiles for each row execute function public.prepare_guest_profile();

create or replace function public.convert_current_guest_to_student(p_alias text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();
begin
  update public.profiles set role_id='student',alias=coalesce(nullif(trim(p_alias),''),alias),converted_at=now(),expires_at=null,active=true
  where id=v_user and role_id='guest' and coalesce(expires_at,now()+interval '1 day')>now();
  if not found then raise exception 'Active guest profile required'; end if;
  return jsonb_build_object('converted',true,'user_id',v_user);
end $$;
grant execute on function public.convert_current_guest_to_student(text) to authenticated;

create or replace function public.cleanup_expired_guests(p_limit integer default 200)
returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer;
begin
  with expired as (
    select id from public.profiles where role_id='guest' and converted_at is null and expires_at<=now()
    order by expires_at for update skip locked limit greatest(1,least(p_limit,1000))
  )
  update public.profiles p set active=false,alias='Invitado caducado',points=0
  from expired e where p.id=e.id;
  get diagnostics v_count=row_count;
  delete from public.enrollments e using public.profiles p where e.student_id=p.id and p.role_id='guest' and p.active=false and p.expires_at<=now();
  return v_count;
end $$;
revoke all on function public.cleanup_expired_guests(integer) from public,anon,authenticated;
grant execute on function public.cleanup_expired_guests(integer) to service_role;

do $$ begin
  perform cron.unschedule(jobid) from cron.job where jobname='omniquest-teacher-digests';
  perform cron.unschedule(jobid) from cron.job where jobname='omniquest-guest-cleanup';
exception when undefined_table then null; end $$;

select cron.schedule('omniquest-teacher-digests','0 * * * *',$$select public.enqueue_due_teacher_digests(now());$$);
select cron.schedule('omniquest-guest-cleanup','17 * * * *',$$select public.cleanup_expired_guests(500);$$);

create or replace function public.invoke_teacher_digest_processor()
returns void language plpgsql security definer set search_path=public,extensions as $$
declare v_url text; v_secret text;
begin
  select decrypted_secret into v_url from vault.decrypted_secrets where name='project_url' limit 1;
  select decrypted_secret into v_secret from vault.decrypted_secrets where name='digest_queue_secret' limit 1;
  if nullif(trim(v_url),'') is null or nullif(trim(v_secret),'') is null then return; end if;
  perform net.http_post(
    url := rtrim(v_url,'/') || '/functions/v1/process-teacher-digests',
    headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',v_secret),
    body := jsonb_build_object('source','pg_cron'),
    timeout_milliseconds := 15000
  );
end $$;
revoke all on function public.invoke_teacher_digest_processor() from public,anon,authenticated;
grant execute on function public.invoke_teacher_digest_processor() to service_role;

do $$ begin
  perform cron.unschedule(jobid) from cron.job where jobname='omniquest-teacher-digest-worker';
exception when undefined_table then null; end $$;
select cron.schedule('omniquest-teacher-digest-worker','*/10 * * * *',$$select public.invoke_teacher_digest_processor();$$);

create or replace function public.get_admin_dashboard_metrics()
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_total_profiles integer:=0; v_teachers_count integer:=0; v_students_count integer:=0;
  v_subjects_count integer:=0; v_classrooms_count integer:=0; v_enrollments_count integer:=0;
  v_active_courses integer:=0; v_archived_courses integer:=0; v_active_classrooms integer:=0;
  v_inactive_users integer:=0; v_courses_without_classrooms integer:=0;
  v_students_without_activity integer:=0; v_classrooms_without_code integer:=0;
begin
  if not public.is_admin() then raise exception 'No autorizado.'; end if;
  select count(*)::integer,
    count(*) filter(where role_id='teacher')::integer,
    count(*) filter(where role_id in('student','guest'))::integer,
    count(*) filter(where active=false)::integer
  into v_total_profiles,v_teachers_count,v_students_count,v_inactive_users
  from public.profiles p
  where not (p.role_id='guest' and p.converted_at is null and p.expires_at<=now());
  select count(*)::integer,count(*) filter(where coalesce(active,true) and not coalesce(is_archived,false))::integer,count(*) filter(where coalesce(is_archived,false))::integer
  into v_subjects_count,v_active_courses,v_archived_courses from public.subjects;
  select count(*)::integer,count(*) filter(where coalesce(active,true))::integer,count(*) filter(where nullif(trim(coalesce(code,'')),'') is null)::integer
  into v_classrooms_count,v_active_classrooms,v_classrooms_without_code from public.classrooms;
  select count(*)::integer into v_enrollments_count from public.enrollments e join public.profiles p on p.id=e.student_id
  where not (p.role_id='guest' and p.converted_at is null and p.expires_at<=now());
  select count(*)::integer into v_courses_without_classrooms from public.subjects s where not exists(select 1 from public.classrooms c where c.subject_id=s.id);
  select count(*)::integer into v_students_without_activity from (
    select distinct e.student_id from public.enrollments e join public.profiles p on p.id=e.student_id
    where not (p.role_id='guest' and p.converted_at is null and p.expires_at<=now())
      and not exists(select 1 from public.subject_scores ss where ss.student_id=e.student_id)
      and not exists(select 1 from public.attempt_history ah where ah.student_id=e.student_id)
  ) x;
  return jsonb_build_object('totalProfiles',v_total_profiles,'teachersCount',v_teachers_count,'studentsCount',v_students_count,
    'subjectsCount',v_subjects_count,'classroomsCount',v_classrooms_count,'enrollmentsCount',v_enrollments_count,
    'activeCourses',v_active_courses,'archivedCourses',v_archived_courses,'activeClassrooms',v_active_classrooms,
    'inactiveUsers',v_inactive_users,'coursesWithoutClassrooms',v_courses_without_classrooms,
    'studentsWithoutActivity',v_students_without_activity,'classroomsWithoutCode',v_classrooms_without_code);
end $$;
grant execute on function public.get_admin_dashboard_metrics() to authenticated;
notify pgrst,'reload schema';
