-- Usage analytics, admin support operations and role-aware global search.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  role text,
  event_name text not null,
  subject_id bigint references public.subjects(id) on delete set null,
  classroom_id bigint references public.classrooms(id) on delete set null,
  topic_id bigint references public.subject_topics(id) on delete set null,
  attempt_id uuid references public.game_attempts(id) on delete set null,
  session_id text,
  properties jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists analytics_events_name_occurred_at_idx
  on public.analytics_events(event_name, occurred_at desc);
create index if not exists analytics_events_user_occurred_at_idx
  on public.analytics_events(user_id, occurred_at desc);
create index if not exists analytics_events_subject_occurred_at_idx
  on public.analytics_events(subject_id, occurred_at desc)
  where subject_id is not null;

alter table public.analytics_events enable row level security;

revoke all on table public.analytics_events from anon, authenticated;
grant select on table public.analytics_events to authenticated;

drop policy if exists "admin_select_analytics_events" on public.analytics_events;
create policy "admin_select_analytics_events"
on public.analytics_events for select to authenticated
using (public.is_admin());

create or replace function public.track_usage_event(
  p_event_name text,
  p_properties jsonb default '{}'::jsonb,
  p_subject_id bigint default null,
  p_classroom_id bigint default null,
  p_topic_id bigint default null,
  p_attempt_id uuid default null,
  p_session_id text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_role text;
  v_event_name text := lower(trim(coalesce(p_event_name, '')));
  v_event_id bigint;
begin
  if v_user_id is null then
    raise exception 'No authenticated user';
  end if;

  if v_event_name not in (
    'game_error',
    'game_resumed',
    'global_search',
    'support_ticket_created'
  ) then
    raise exception 'Unsupported analytics event';
  end if;

  select role_id into v_role
  from public.profiles
  where id = v_user_id;

  insert into public.analytics_events (
    user_id,
    role,
    event_name,
    subject_id,
    classroom_id,
    topic_id,
    attempt_id,
    session_id,
    properties
  ) values (
    v_user_id,
    v_role,
    v_event_name,
    p_subject_id,
    p_classroom_id,
    p_topic_id,
    p_attempt_id,
    nullif(trim(coalesce(p_session_id, '')), ''),
    coalesce(p_properties, '{}'::jsonb)
  )
  returning id into v_event_id;

  return v_event_id;
end;
$$;

revoke execute on function public.track_usage_event(text, jsonb, bigint, bigint, bigint, uuid, text) from public, anon;
grant execute on function public.track_usage_event(text, jsonb, bigint, bigint, bigint, uuid, text) to authenticated;

create or replace function public.log_game_attempt_analytics()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_event_name text;
begin
  select role_id into v_role
  from public.profiles
  where id = new.student_id;

  if tg_op = 'INSERT' then
    v_event_name := 'game_started';
  elsif tg_op = 'UPDATE' and old.status is distinct from new.status then
    if new.status = 'abandoned' then
      v_event_name := 'game_abandoned';
    elsif new.status = 'finished' then
      v_event_name := 'game_finished';
    end if;
  end if;

  if v_event_name is not null then
    insert into public.analytics_events (
      user_id,
      role,
      event_name,
      subject_id,
      classroom_id,
      topic_id,
      attempt_id,
      properties,
      occurred_at
    ) values (
      new.student_id,
      coalesce(v_role, 'student'),
      v_event_name,
      new.subject_id,
      new.classroom_id,
      new.topic_id,
      new.id,
      jsonb_build_object(
        'status', new.status,
        'total_score', coalesce(new.total_score, 0),
        'correct_answers', coalesce(new.correct_answers, 0)
      ),
      case
        when v_event_name in ('game_finished', 'game_abandoned') then coalesce(new.finished_at, now())
        else coalesce(new.started_at, now())
      end
    );
  end if;

  return new;
end;
$$;

drop trigger if exists log_game_attempt_analytics_insert on public.game_attempts;
create trigger log_game_attempt_analytics_insert
after insert on public.game_attempts
for each row execute function public.log_game_attempt_analytics();

drop trigger if exists log_game_attempt_analytics_status on public.game_attempts;
create trigger log_game_attempt_analytics_status
after update of status on public.game_attempts
for each row execute function public.log_game_attempt_analytics();

create or replace function public.log_badge_unlock_analytics()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.analytics_events (
    user_id,
    role,
    event_name,
    properties,
    occurred_at
  ) values (
    new.student_id,
    'student',
    'badge_unlocked',
    jsonb_build_object(
      'badge_id', new.badge_id,
      'reward_xp', coalesce(new.reward_xp, 0)
    ),
    coalesce(new.awarded_at, now())
  );

  return new;
end;
$$;

drop trigger if exists log_badge_unlock_analytics on public.student_badges;
create trigger log_badge_unlock_analytics
after insert on public.student_badges
for each row execute function public.log_badge_unlock_analytics();

create or replace function public.get_admin_usage_analytics(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_days integer := least(greatest(coalesce(p_days, 30), 1), 365);
  v_since timestamptz;
  v_result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  v_since := now() - make_interval(days => v_days);

  select jsonb_build_object(
    'days', v_days,
    'game_started', count(*) filter (where event_name = 'game_started'),
    'game_finished', count(*) filter (where event_name = 'game_finished'),
    'game_abandoned', count(*) filter (where event_name = 'game_abandoned'),
    'game_errors', count(*) filter (where event_name = 'game_error'),
    'badges_unlocked', count(*) filter (where event_name = 'badge_unlocked'),
    'active_users', count(distinct user_id),
    'completion_rate', case
      when count(*) filter (where event_name = 'game_started') = 0 then 0
      else round(
        100.0 * count(*) filter (where event_name = 'game_finished')
        / nullif(count(*) filter (where event_name = 'game_started'), 0),
        1
      )
    end,
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object(
        'day', day,
        'game_started', game_started,
        'game_finished', game_finished,
        'game_abandoned', game_abandoned,
        'game_errors', game_errors,
        'badges_unlocked', badges_unlocked
      ) order by day)
      from (
        select
          occurred_at::date as day,
          count(*) filter (where event_name = 'game_started') as game_started,
          count(*) filter (where event_name = 'game_finished') as game_finished,
          count(*) filter (where event_name = 'game_abandoned') as game_abandoned,
          count(*) filter (where event_name = 'game_error') as game_errors,
          count(*) filter (where event_name = 'badge_unlocked') as badges_unlocked
        from public.analytics_events
        where occurred_at >= v_since
        group by occurred_at::date
      ) daily_rows
    ), '[]'::jsonb)
  ) into v_result
  from public.analytics_events
  where occurred_at >= v_since;

  return coalesce(v_result, jsonb_build_object(
    'days', v_days,
    'game_started', 0,
    'game_finished', 0,
    'game_abandoned', 0,
    'game_errors', 0,
    'badges_unlocked', 0,
    'active_users', 0,
    'completion_rate', 0,
    'daily', '[]'::jsonb
  ));
end;
$$;

revoke execute on function public.get_admin_usage_analytics(integer) from public, anon;
grant execute on function public.get_admin_usage_analytics(integer) to authenticated;

-- Support tickets: users may create/read their own tickets, but only admins may manage them.
alter table public.user_support_tickets
  add column if not exists admin_response text,
  add column if not exists assigned_admin_id uuid references public.profiles(id) on delete set null,
  add column if not exists resolved_at timestamptz,
  add column if not exists last_response_at timestamptz;

create index if not exists user_support_tickets_status_created_at_idx
  on public.user_support_tickets(status, created_at desc);
create index if not exists user_support_tickets_priority_created_at_idx
  on public.user_support_tickets(priority, created_at desc);

drop policy if exists "user_support_tickets_self" on public.user_support_tickets;
drop policy if exists "user_support_tickets_select_self" on public.user_support_tickets;
drop policy if exists "user_support_tickets_insert_self" on public.user_support_tickets;
drop policy if exists "user_support_tickets_update_self" on public.user_support_tickets;
drop policy if exists "user_support_tickets_delete_self" on public.user_support_tickets;

create policy "user_support_tickets_select_self"
on public.user_support_tickets for select to authenticated
using (user_id = auth.uid());

create policy "user_support_tickets_insert_self"
on public.user_support_tickets for insert to authenticated
with check (
  user_id = auth.uid()
  and role = case
    when (select p.role_id from public.profiles p where p.id = auth.uid()) = 'teacher' then 'teacher'
    else 'student'
  end
  and status = 'open'
  and priority in ('low', 'medium', 'high')
);

create or replace function public.get_admin_support_tickets_page(
  p_search text default null,
  p_status text default null,
  p_priority text default null,
  p_role text default null,
  p_limit integer default 25,
  p_offset integer default 0
)
returns table (
  id bigint,
  user_id uuid,
  user_alias text,
  user_email text,
  role text,
  category text,
  subject text,
  message text,
  contact_email text,
  priority text,
  status text,
  admin_response text,
  assigned_admin_id uuid,
  resolved_at timestamptz,
  last_response_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 25), 1), 100);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_search text := nullif(trim(coalesce(p_search, '')), '');
  v_status text := nullif(lower(trim(coalesce(p_status, ''))), '');
  v_priority text := nullif(lower(trim(coalesce(p_priority, ''))), '');
  v_role text := nullif(lower(trim(coalesce(p_role, ''))), '');
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  return query
  with filtered as (
    select t.*, p.alias as user_alias, p.email as user_email
    from public.user_support_tickets t
    left join public.profiles p on p.id = t.user_id
    where (v_status is null or t.status = v_status)
      and (v_priority is null or t.priority = v_priority)
      and (v_role is null or t.role = v_role)
      and (
        v_search is null
        or concat_ws(' ', t.subject, t.message, t.category, t.contact_email, t.admin_response, p.alias, p.email) ilike '%' || v_search || '%'
      )
  )
  select
    f.id,
    f.user_id,
    f.user_alias,
    f.user_email,
    f.role,
    f.category,
    f.subject,
    f.message,
    f.contact_email,
    f.priority,
    f.status,
    f.admin_response,
    f.assigned_admin_id,
    f.resolved_at,
    f.last_response_at,
    f.created_at,
    f.updated_at,
    count(*) over() as total_count
  from filtered f
  order by
    case f.priority when 'high' then 1 when 'medium' then 2 else 3 end,
    case f.status when 'open' then 1 when 'in_progress' then 2 when 'resolved' then 3 else 4 end,
    f.created_at desc,
    f.id desc
  limit v_limit offset v_offset;
end;
$$;

create or replace function public.admin_update_support_ticket(
  p_ticket_id bigint,
  p_status text,
  p_priority text default null,
  p_admin_response text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := auth.uid();
  v_ticket public.user_support_tickets%rowtype;
  v_status text := lower(trim(coalesce(p_status, '')));
  v_priority text := nullif(lower(trim(coalesce(p_priority, ''))), '');
  v_response text := nullif(trim(coalesce(p_admin_response, '')), '');
  v_audience text;
  v_action_url text;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  if v_status not in ('open', 'in_progress', 'resolved', 'closed') then
    raise exception 'Invalid support status';
  end if;

  if v_priority is not null and v_priority not in ('low', 'medium', 'high') then
    raise exception 'Invalid support priority';
  end if;

  update public.user_support_tickets
  set
    status = v_status,
    priority = coalesce(v_priority, priority),
    admin_response = coalesce(v_response, admin_response),
    assigned_admin_id = v_admin_id,
    last_response_at = case when v_response is not null then now() else last_response_at end,
    resolved_at = case when v_status in ('resolved', 'closed') then coalesce(resolved_at, now()) else null end,
    updated_at = now()
  where id = p_ticket_id
  returning * into v_ticket;

  if not found then
    raise exception 'Support ticket not found';
  end if;

  insert into public.admin_audit_logs (admin_id, action, target_table, target_id, metadata)
  values (
    v_admin_id,
    'admin.support.update',
    'user_support_tickets',
    v_ticket.id::text,
    jsonb_build_object(
      'status', v_ticket.status,
      'priority', v_ticket.priority,
      'user_id', v_ticket.user_id,
      'has_response', v_ticket.admin_response is not null
    )
  );

  if v_response is not null then
    v_audience := case when v_ticket.role = 'teacher' then 'teacher' else 'student' end;
    v_action_url := case when v_audience = 'teacher' then '/(teacher)/help-center' else '/(student)/help-center' end;

    perform public.create_notification(
      v_ticket.user_id,
      v_audience,
      'announcement',
      'Soporte ha respondido',
      concat('Tu ticket "', v_ticket.subject, '" tiene una nueva respuesta.'),
      'chatbubble-ellipses-outline',
      '#8B5CF6',
      v_action_url,
      'user_support_tickets',
      v_ticket.id::text,
      jsonb_build_object(
        'ticket_id', v_ticket.id,
        'status', v_ticket.status,
        'preference_category', 'system'
      ),
      concat(
        'support-ticket:',
        v_ticket.id,
        ':response:',
        coalesce(v_ticket.last_response_at, now())::text
      )
    );
  end if;

  return jsonb_build_object(
    'id', v_ticket.id,
    'status', v_ticket.status,
    'priority', v_ticket.priority,
    'admin_response', v_ticket.admin_response,
    'updated_at', v_ticket.updated_at
  );
end;
$$;

revoke execute on function public.get_admin_support_tickets_page(text, text, text, text, integer, integer) from public, anon;
grant execute on function public.get_admin_support_tickets_page(text, text, text, text, integer, integer) to authenticated;
revoke execute on function public.admin_update_support_ticket(bigint, text, text, text) from public, anon;
grant execute on function public.admin_update_support_ticket(bigint, text, text, text) to authenticated;

-- One role-aware global search RPC avoids duplicating search logic in every screen.
create or replace function public.search_app_entities(
  p_query text,
  p_limit integer default 12
)
returns table (
  entity_type text,
  entity_id text,
  title text,
  subtitle text,
  role_id text,
  subject_id bigint,
  classroom_id bigint,
  relevance integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_role text;
  v_query text := lower(trim(coalesce(p_query, '')));
  v_limit integer := least(greatest(coalesce(p_limit, 12), 1), 30);
begin
  if v_user_id is null then
    raise exception 'No authenticated user';
  end if;

  if length(v_query) < 2 then
    return;
  end if;

  select p.role_id into v_role
  from public.profiles p
  where p.id = v_user_id and coalesce(p.active, true);

  if v_role = 'admin' then
    return query
    with candidates as (
      select
        'profile'::text as entity_type,
        p.id::text as entity_id,
        coalesce(p.alias, p.email, 'Usuario')::text as title,
        concat_ws(' · ', case when p.role_id = 'teacher' then 'Profesor' else 'Alumno' end, p.email)::text as subtitle,
        p.role_id::text as role_id,
        null::bigint as subject_id,
        null::bigint as classroom_id,
        case
          when lower(coalesce(p.alias, '')) = v_query then 0
          when lower(coalesce(p.alias, '')) like v_query || '%' then 1
          else 3
        end as relevance
      from public.profiles p
      where p.role_id in ('teacher', 'student', 'guest')
        and lower(concat_ws(' ', p.alias, p.email, p.role_id)) like '%' || v_query || '%'

      union all

      select
        'subject',
        s.id::text,
        s.name,
        concat_ws(' · ', 'Curso', p.alias, case when coalesce(s.is_archived, false) then 'Archivado' else null end),
        null,
        s.id,
        null,
        case when lower(s.name) = v_query then 0 when lower(s.name) like v_query || '%' then 1 else 3 end
      from public.subjects s
      left join public.profiles p on p.id = s.teacher_id
      where lower(concat_ws(' ', s.name, s.code, p.alias, p.email)) like '%' || v_query || '%'

      union all

      select
        'classroom',
        c.id::text,
        c.name,
        concat_ws(' · ', 'Clase', s.name, c.code),
        null,
        c.subject_id,
        c.id,
        case when lower(c.name) = v_query then 0 when lower(c.name) like v_query || '%' then 1 else 3 end
      from public.classrooms c
      join public.subjects s on s.id = c.subject_id
      where lower(concat_ws(' ', c.name, c.code, s.name)) like '%' || v_query || '%'
    )
    select c.entity_type, c.entity_id, c.title, c.subtitle, c.role_id, c.subject_id, c.classroom_id, c.relevance
    from candidates c
    order by c.relevance, c.title
    limit v_limit;
    return;
  end if;

  if v_role = 'teacher' then
    return query
    with teacher_subjects as (
      select s.id, s.name, s.code
      from public.subjects s
      where s.teacher_id = v_user_id
    ),
    student_candidates as (
      select distinct on (p.id)
        'profile'::text as entity_type,
        p.id::text as entity_id,
        coalesce(p.alias, p.email, 'Alumno')::text as title,
        concat_ws(' · ', 'Alumno', p.email, ts.name)::text as subtitle,
        p.role_id::text as role_id,
        ts.id::bigint as subject_id,
        e.classroom_id::bigint as classroom_id,
        case
          when lower(coalesce(p.alias, '')) = v_query then 0
          when lower(coalesce(p.alias, '')) like v_query || '%' then 1
          else 3
        end as relevance
      from public.enrollments e
      join teacher_subjects ts on ts.id = e.subject_id
      join public.profiles p on p.id = e.student_id
      where lower(concat_ws(' ', p.alias, p.email, ts.name)) like '%' || v_query || '%'
      order by p.id, ts.id
    ),
    candidates as (
      select * from student_candidates

      union all

      select
        'subject',
        ts.id::text,
        ts.name,
        concat_ws(' · ', 'Curso', ts.code),
        null,
        ts.id,
        null,
        case when lower(ts.name) = v_query then 0 when lower(ts.name) like v_query || '%' then 1 else 3 end
      from teacher_subjects ts
      where lower(concat_ws(' ', ts.name, ts.code)) like '%' || v_query || '%'

      union all

      select
        'classroom',
        c.id::text,
        c.name,
        concat_ws(' · ', 'Clase', ts.name, c.code),
        null,
        c.subject_id,
        c.id,
        case when lower(c.name) = v_query then 0 when lower(c.name) like v_query || '%' then 1 else 3 end
      from public.classrooms c
      join teacher_subjects ts on ts.id = c.subject_id
      where lower(concat_ws(' ', c.name, c.code, ts.name)) like '%' || v_query || '%'
    )
    select c.entity_type, c.entity_id, c.title, c.subtitle, c.role_id, c.subject_id, c.classroom_id, c.relevance
    from candidates c
    order by c.relevance, c.title
    limit v_limit;
    return;
  end if;

  raise exception 'Global search is available only to teachers and admins';
end;
$$;

revoke execute on function public.search_app_entities(text, integer) from public, anon;
grant execute on function public.search_app_entities(text, integer) to authenticated;

notify pgrst, 'reload schema';
