create extension if not exists pgcrypto;

create table if not exists public.manual_review_settings (
  teacher_id uuid primary key references public.profiles(id) on delete cascade,
  sla_hours integer not null default 48 check (sla_hours between 1 and 720),
  updated_at timestamptz not null default now()
);

create table if not exists public.manual_review_rubrics (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 100),
  criteria jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint manual_review_rubrics_criteria_array check (jsonb_typeof(criteria) = 'array')
);

create index if not exists manual_review_rubrics_teacher_subject_idx
  on public.manual_review_rubrics(teacher_id, subject_id, active, updated_at desc);

create table if not exists public.manual_review_comment_templates (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 2 and 80),
  body text not null check (char_length(trim(body)) between 1 and 2000),
  audience text not null default 'student' check (audience in ('student', 'internal')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists manual_review_comment_templates_teacher_idx
  on public.manual_review_comment_templates(teacher_id, active, updated_at desc);

create table if not exists public.manual_review_saved_filters (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 80),
  filters jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint manual_review_saved_filters_object check (jsonb_typeof(filters) = 'object')
);

create unique index if not exists manual_review_saved_filters_teacher_name_idx
  on public.manual_review_saved_filters(teacher_id, lower(name));

alter table public.attempt_history
  add column if not exists manual_review_due_at timestamptz,
  add column if not exists manual_review_assigned_to uuid references public.profiles(id) on delete set null,
  add column if not exists manual_review_started_at timestamptz,
  add column if not exists manual_review_rubric_id uuid references public.manual_review_rubrics(id) on delete set null,
  add column if not exists manual_review_rubric_result jsonb;

create index if not exists attempt_history_manual_review_sla_idx
  on public.attempt_history(manual_review_status, manual_review_due_at, manual_review_assigned_to)
  where manual_review_status in ('pending', 'in_review', 'needs_changes');

create table if not exists public.manual_review_history (
  id bigint generated by default as identity primary key,
  attempt_history_id bigint not null references public.attempt_history(id) on delete restrict,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text,
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists manual_review_history_attempt_created_idx
  on public.manual_review_history(attempt_history_id, created_at desc, id desc);

alter table public.manual_review_settings enable row level security;
alter table public.manual_review_rubrics enable row level security;
alter table public.manual_review_comment_templates enable row level security;
alter table public.manual_review_saved_filters enable row level security;
alter table public.manual_review_history enable row level security;

revoke all on public.manual_review_settings from public, anon, authenticated;
revoke all on public.manual_review_rubrics from public, anon, authenticated;
revoke all on public.manual_review_comment_templates from public, anon, authenticated;
revoke all on public.manual_review_saved_filters from public, anon, authenticated;
revoke all on public.manual_review_history from public, anon, authenticated;

grant select on public.manual_review_settings to authenticated;
grant select on public.manual_review_rubrics to authenticated;
grant select on public.manual_review_comment_templates to authenticated;
grant select on public.manual_review_saved_filters to authenticated;
grant select on public.manual_review_history to authenticated;

drop policy if exists "manual_review_settings_select_own" on public.manual_review_settings;
create policy "manual_review_settings_select_own" on public.manual_review_settings
for select to authenticated using (teacher_id = auth.uid() or public.is_admin());

drop policy if exists "manual_review_rubrics_select_own" on public.manual_review_rubrics;
create policy "manual_review_rubrics_select_own" on public.manual_review_rubrics
for select to authenticated using (teacher_id = auth.uid() or public.is_admin());

drop policy if exists "manual_review_templates_select_own" on public.manual_review_comment_templates;
create policy "manual_review_templates_select_own" on public.manual_review_comment_templates
for select to authenticated using (teacher_id = auth.uid() or public.is_admin());

drop policy if exists "manual_review_filters_select_own" on public.manual_review_saved_filters;
create policy "manual_review_filters_select_own" on public.manual_review_saved_filters
for select to authenticated using (teacher_id = auth.uid() or public.is_admin());

drop policy if exists "manual_review_history_select_participants" on public.manual_review_history;
create policy "manual_review_history_select_participants" on public.manual_review_history
for select to authenticated using (
  public.is_admin()
  or exists (
    select 1
    from public.attempt_history ah
    join public.questions q on q.id = ah.question_id
    join public.subjects s on s.id = q.subject_id
    where ah.id = manual_review_history.attempt_history_id
      and (s.teacher_id = auth.uid() or ah.manual_review_assigned_to = auth.uid())
  )
);

create or replace function public.prepare_manual_review_sla()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid;
  v_sla_hours integer := 48;
begin
  if new.manual_review_status in ('pending', 'in_review', 'needs_changes') then
    select s.teacher_id into v_teacher_id
    from public.questions q
    join public.subjects s on s.id = q.subject_id
    where q.id = new.question_id;

    select coalesce(mrs.sla_hours, 48) into v_sla_hours
    from public.manual_review_settings mrs
    where mrs.teacher_id = v_teacher_id;
    v_sla_hours := coalesce(v_sla_hours, 48);

    if new.manual_review_due_at is null then
      new.manual_review_due_at := coalesce(new.attempted_at, new.created_at, now()) + make_interval(hours => v_sla_hours);
    end if;
    if new.manual_review_status = 'in_review' and new.manual_review_started_at is null then
      new.manual_review_started_at := now();
    end if;
  else
    new.manual_review_due_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists prepare_manual_review_sla_trigger on public.attempt_history;
create trigger prepare_manual_review_sla_trigger
before insert or update of manual_review_status, question_id on public.attempt_history
for each row execute function public.prepare_manual_review_sla();

update public.attempt_history ah
set manual_review_due_at = coalesce(ah.attempted_at, ah.created_at, now()) + interval '48 hours'
where ah.manual_review_status in ('pending', 'in_review', 'needs_changes')
  and ah.manual_review_due_at is null;

create or replace function public.capture_manual_review_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_changed boolean;
  v_event text;
begin
  v_changed := old.manual_review_status is distinct from new.manual_review_status
    or old.manual_review_assigned_to is distinct from new.manual_review_assigned_to
    or old.manual_review_rubric_id is distinct from new.manual_review_rubric_id
    or old.manual_review_rubric_result is distinct from new.manual_review_rubric_result
    or old.earned_points is distinct from new.earned_points;
  if not v_changed then return new; end if;

  v_event := case
    when old.manual_review_status is distinct from new.manual_review_status then 'status_changed'
    when old.manual_review_assigned_to is distinct from new.manual_review_assigned_to then 'assigned'
    when old.manual_review_rubric_result is distinct from new.manual_review_rubric_result then 'rubric_scored'
    else 'review_updated'
  end;

  insert into public.manual_review_history(
    attempt_history_id, actor_id, event_type, from_status, to_status, before_state, after_state
  ) values (
    new.id,
    auth.uid(),
    v_event,
    old.manual_review_status,
    new.manual_review_status,
    jsonb_build_object(
      'status', old.manual_review_status,
      'assigned_to', old.manual_review_assigned_to,
      'rubric_id', old.manual_review_rubric_id,
      'earned_points', old.earned_points
    ),
    jsonb_build_object(
      'status', new.manual_review_status,
      'assigned_to', new.manual_review_assigned_to,
      'rubric_id', new.manual_review_rubric_id,
      'earned_points', new.earned_points
    )
  );
  return new;
end;
$$;

drop trigger if exists capture_manual_review_history_trigger on public.attempt_history;
create trigger capture_manual_review_history_trigger
after update of manual_review_status, manual_review_assigned_to, manual_review_rubric_id, manual_review_rubric_result, earned_points
on public.attempt_history
for each row execute function public.capture_manual_review_history();

create or replace function public.prevent_manual_review_history_mutation()
returns trigger language plpgsql set search_path = public as $$
begin
  raise exception 'Manual review history is immutable';
end;
$$;

drop trigger if exists prevent_manual_review_history_update on public.manual_review_history;
create trigger prevent_manual_review_history_update
before update or delete on public.manual_review_history
for each row execute function public.prevent_manual_review_history_mutation();

create or replace function public.get_teacher_manual_review_queue(
  p_subject_id bigint default null,
  p_classroom_id bigint default null,
  p_status text default null,
  p_search text default null,
  p_limit integer default 20,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 100);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_result jsonb;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;

  with filtered as (
    select
      ah.id,
      ah.student_id,
      coalesce(p.alias, split_part(p.email, '@', 1), 'Alumno') as student_name,
      p.email as student_email,
      ah.question_id,
      q.text as question_text,
      ah.submitted_answer_text as answer_text,
      ah.submitted_answer_payload as answer_payload,
      ah.manual_review_status as status,
      ah.attempted_at,
      ah.reviewed_at,
      ah.review_notes,
      ah.earned_points,
      q.points_base as possible_points,
      ah.time_taken_seconds,
      s.id as subject_id,
      s.name as subject_name,
      c.id as classroom_id,
      coalesce(c.name, 'Sin clase') as classroom_name,
      st.id as topic_id,
      st.title as topic_name,
      ah.manual_review_due_at as due_at,
      ah.manual_review_assigned_to as assigned_to,
      coalesce(assignee.alias, split_part(assignee.email, '@', 1)) as assigned_to_name,
      ah.manual_review_rubric_id as rubric_id,
      rubric.name as rubric_name,
      ah.manual_review_rubric_result as rubric_result,
      greatest(0, extract(epoch from (now() - coalesce(ah.attempted_at, ah.created_at, now())))::bigint) as pending_seconds,
      (ah.manual_review_due_at is not null and ah.manual_review_due_at < now()) as is_overdue,
      (select count(*) from public.manual_review_comments mrc where mrc.attempt_history_id = ah.id)::integer as comments_count,
      (select mrc.body from public.manual_review_comments mrc where mrc.attempt_history_id = ah.id order by mrc.created_at desc, mrc.id desc limit 1) as latest_comment
    from public.attempt_history ah
    join public.questions q on q.id = ah.question_id
    join public.subjects s on s.id = q.subject_id
    left join public.classrooms c on c.id = coalesce(q.classroom_id, (select ga.classroom_id from public.game_attempts ga where ga.id = ah.attempt_id))
    left join public.subject_topics st on st.id = q.topic_id
    left join public.profiles p on p.id = ah.student_id
    left join public.profiles assignee on assignee.id = ah.manual_review_assigned_to
    left join public.manual_review_rubrics rubric on rubric.id = ah.manual_review_rubric_id
    where q.type = 'open_answer'
      and ah.manual_review_status <> 'not_required'
      and (public.is_admin() or s.teacher_id = v_user_id or ah.manual_review_assigned_to = v_user_id)
      and (p_subject_id is null or q.subject_id = p_subject_id)
      and (p_classroom_id is null or coalesce(q.classroom_id, c.id) = p_classroom_id)
      and (nullif(trim(coalesce(p_status, '')), '') is null or ah.manual_review_status = p_status)
      and (
        nullif(trim(coalesce(p_search, '')), '') is null
        or q.text ilike '%' || trim(p_search) || '%'
        or coalesce(ah.submitted_answer_text, '') ilike '%' || trim(p_search) || '%'
        or coalesce(p.alias, '') ilike '%' || trim(p_search) || '%'
        or coalesce(p.email, '') ilike '%' || trim(p_search) || '%'
        or s.name ilike '%' || trim(p_search) || '%'
      )
  ), page as (
    select * from filtered
    order by is_overdue desc,
      case status when 'pending' then 1 when 'needs_changes' then 2 when 'in_review' then 3 else 4 end,
      due_at asc nulls last, attempted_at asc, id asc
    limit v_limit offset v_offset
  )
  select jsonb_build_object(
    'items', coalesce((select jsonb_agg(to_jsonb(page) order by page.is_overdue desc, page.due_at asc nulls last, page.id) from page), '[]'::jsonb),
    'total', (select count(*) from filtered),
    'summary', jsonb_build_object(
      'pending', (select count(*) from filtered where status = 'pending'),
      'in_review', (select count(*) from filtered where status = 'in_review'),
      'needs_changes', (select count(*) from filtered where status = 'needs_changes'),
      'overdue', (select count(*) from filtered where is_overdue)
    )
  ) into v_result;
  return coalesce(v_result, jsonb_build_object('items', '[]'::jsonb, 'total', 0, 'summary', '{}'::jsonb));
end;
$$;

create or replace function public.get_manual_review_configuration()
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_result jsonb;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if not public.is_admin() and not exists (select 1 from public.profiles where id = v_user_id and role_id = 'teacher') then
    raise exception 'Teacher access required';
  end if;
  insert into public.manual_review_settings(teacher_id) values (v_user_id) on conflict (teacher_id) do nothing;

  select jsonb_build_object(
    'slaHours', (select sla_hours from public.manual_review_settings where teacher_id = v_user_id),
    'rubrics', coalesce((select jsonb_agg(to_jsonb(r) order by r.updated_at desc) from public.manual_review_rubrics r where r.teacher_id = v_user_id and r.active), '[]'::jsonb),
    'templates', coalesce((select jsonb_agg(to_jsonb(t) order by t.updated_at desc) from public.manual_review_comment_templates t where t.teacher_id = v_user_id and t.active), '[]'::jsonb),
    'savedFilters', coalesce((select jsonb_agg(to_jsonb(f) order by f.updated_at desc) from public.manual_review_saved_filters f where f.teacher_id = v_user_id), '[]'::jsonb),
    'assignees', coalesce((select jsonb_agg(jsonb_build_object('id', p.id, 'name', coalesce(p.alias, split_part(p.email, '@', 1), 'Profesor')) order by p.alias) from public.profiles p where p.role_id = 'teacher' and coalesce(p.active, true)), '[]'::jsonb),
    'subjects', coalesce((select jsonb_agg(jsonb_build_object('id', s.id, 'name', s.name) order by s.name) from public.subjects s where s.teacher_id = v_user_id and not s.is_archived), '[]'::jsonb),
    'classrooms', coalesce((select jsonb_agg(jsonb_build_object('id', c.id, 'subject_id', c.subject_id, 'name', c.name) order by c.name) from public.classrooms c join public.subjects s on s.id = c.subject_id where s.teacher_id = v_user_id and c.active), '[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.save_manual_review_settings(p_sla_hours integer)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid();
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_sla_hours not between 1 and 720 then raise exception 'Invalid SLA'; end if;
  insert into public.manual_review_settings(teacher_id, sla_hours, updated_at)
  values (v_user_id, p_sla_hours, now())
  on conflict (teacher_id) do update set sla_hours = excluded.sla_hours, updated_at = now();
  return jsonb_build_object('slaHours', p_sla_hours);
end;
$$;

create or replace function public.save_manual_review_rubric(p_id uuid, p_name text, p_subject_id bigint, p_criteria jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if jsonb_typeof(p_criteria) <> 'array' or jsonb_array_length(p_criteria) = 0 then raise exception 'Rubric requires criteria'; end if;
  if p_subject_id is not null and not exists (select 1 from public.subjects where id = p_subject_id and teacher_id = v_user_id) then raise exception 'Invalid subject'; end if;
  if p_id is null then
    insert into public.manual_review_rubrics(teacher_id, subject_id, name, criteria)
    values (v_user_id, p_subject_id, trim(p_name), p_criteria) returning id into v_id;
  else
    update public.manual_review_rubrics set subject_id = p_subject_id, name = trim(p_name), criteria = p_criteria, updated_at = now()
    where id = p_id and teacher_id = v_user_id returning id into v_id;
    if v_id is null then raise exception 'Rubric not found'; end if;
  end if;
  return v_id;
end;
$$;

create or replace function public.save_manual_review_template(p_id uuid, p_title text, p_body text, p_audience text)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_audience not in ('student', 'internal') then raise exception 'Invalid audience'; end if;
  if p_id is null then
    insert into public.manual_review_comment_templates(teacher_id, title, body, audience)
    values (v_user_id, trim(p_title), trim(p_body), p_audience) returning id into v_id;
  else
    update public.manual_review_comment_templates set title = trim(p_title), body = trim(p_body), audience = p_audience, updated_at = now()
    where id = p_id and teacher_id = v_user_id returning id into v_id;
    if v_id is null then raise exception 'Template not found'; end if;
  end if;
  return v_id;
end;
$$;

create or replace function public.save_manual_review_filter(p_id uuid, p_name text, p_filters jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if jsonb_typeof(p_filters) <> 'object' then raise exception 'Invalid filters'; end if;
  if p_id is null then
    insert into public.manual_review_saved_filters(teacher_id, name, filters)
    values (v_user_id, trim(p_name), p_filters)
    on conflict (teacher_id, (lower(name))) do update set filters = excluded.filters, updated_at = now()
    returning id into v_id;
  else
    update public.manual_review_saved_filters set name = trim(p_name), filters = p_filters, updated_at = now()
    where id = p_id and teacher_id = v_user_id returning id into v_id;
    if v_id is null then raise exception 'Filter not found'; end if;
  end if;
  return v_id;
end;
$$;

create or replace function public.assign_manual_review_attempts(p_attempt_ids bigint[], p_assignee_id uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_count integer;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_assignee_id is not null and not exists (select 1 from public.profiles where id = p_assignee_id and role_id = 'teacher' and coalesce(active, true)) then raise exception 'Invalid assignee'; end if;
  update public.attempt_history ah
  set manual_review_assigned_to = p_assignee_id
  from public.questions q join public.subjects s on s.id = q.subject_id
  where ah.question_id = q.id and ah.id = any(coalesce(p_attempt_ids, '{}'::bigint[]))
    and (s.teacher_id = v_user_id or public.is_admin() or ah.manual_review_assigned_to = v_user_id)
    and ah.manual_review_status in ('pending', 'in_review', 'needs_changes');
  get diagnostics v_count = row_count;
  if p_assignee_id is not null and p_assignee_id <> v_user_id and v_count > 0 then
    perform public.create_notification(p_assignee_id, 'teacher', 'manual_review', 'Revisiones asignadas', format('Se te han asignado %s respuestas abiertas.', v_count), 'create-outline', '#38BDF8', '/(teacher)/reviews', 'attempt_history', null, jsonb_build_object('count', v_count, 'preference_category', 'system'), 'manual-review-assignment:' || p_assignee_id::text || ':' || extract(epoch from date_trunc('minute', now()))::bigint::text);
  end if;
  return jsonb_build_object('updated', v_count);
end;
$$;

create or replace function public.get_manual_review_thread(p_attempt_history_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_student_id uuid;
  v_teacher_id uuid;
  v_assignee_id uuid;
  v_result jsonb;
begin
  if v_user_id is null then raise exception 'No hay sesión activa.'; end if;

  select ah.student_id, s.teacher_id, ah.manual_review_assigned_to
  into v_student_id, v_teacher_id, v_assignee_id
  from public.attempt_history ah
  join public.questions q on q.id = ah.question_id
  join public.subjects s on s.id = q.subject_id
  where ah.id = p_attempt_history_id;

  if not found then raise exception 'Intento no encontrado.'; end if;
  if v_user_id <> v_student_id and v_user_id <> v_teacher_id and v_user_id is distinct from v_assignee_id and not public.is_admin() then
    raise exception 'No puedes consultar esta revisión.';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', c.id,
    'author_id', c.author_id,
    'author_name', coalesce(p.alias, split_part(p.email, '@', 1), 'Usuario'),
    'audience', c.audience,
    'body', c.body,
    'created_at', c.created_at
  ) order by c.created_at asc, c.id asc), '[]'::jsonb)
  into v_result
  from public.manual_review_comments c
  left join public.profiles p on p.id = c.author_id
  where c.attempt_history_id = p_attempt_history_id
    and (v_user_id = v_teacher_id or v_user_id = v_assignee_id or public.is_admin() or c.audience = 'student');

  return v_result;
end;
$$;

create or replace function public.add_manual_review_comment(
  p_attempt_history_id bigint,
  p_body text,
  p_audience text default 'student'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_comment public.manual_review_comments%rowtype;
  v_student_id uuid;
begin
  if v_user_id is null then raise exception 'No hay sesión activa.'; end if;
  if nullif(trim(coalesce(p_body, '')), '') is null then raise exception 'Escribe un comentario.'; end if;
  if p_audience not in ('student', 'internal') then raise exception 'La visibilidad del comentario no es válida.'; end if;

  select ah.student_id
  into v_student_id
  from public.attempt_history ah
  join public.questions q on q.id = ah.question_id
  join public.subjects s on s.id = q.subject_id
  where ah.id = p_attempt_history_id
    and (s.teacher_id = v_user_id or ah.manual_review_assigned_to = v_user_id or public.is_admin());

  if not found then raise exception 'No puedes comentar esta revisión.'; end if;

  insert into public.manual_review_comments(attempt_history_id, author_id, audience, body)
  values (p_attempt_history_id, v_user_id, p_audience, trim(p_body))
  returning * into v_comment;

  if p_audience = 'student' then
    perform public.create_notification(
      v_student_id,
      'student',
      'manual_review',
      'Nuevo comentario del profesor',
      left(trim(p_body), 180),
      'chatbubble-ellipses-outline',
      '#A78BFA',
      '/(student)/activity-log',
      'attempt_history',
      p_attempt_history_id::text,
      jsonb_build_object('attempt_history_id', p_attempt_history_id),
      concat('manual-review-comment:', v_comment.id)
    );
  end if;

  return to_jsonb(v_comment);
end;
$$;

create or replace function public.review_open_answer_attempt_assigned(
  p_attempt_history_id bigint,
  p_status text,
  p_notes text default null,
  p_comment_audience text default 'student'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_attempt public.attempt_history%rowtype;
  v_question public.questions%rowtype;
  v_classroom_id bigint;
  v_delta_points integer := 0;
  v_delta_correct integer := 0;
  v_new_earned_points integer := 0;
  v_new_is_correct boolean := false;
  v_student_id uuid;
  v_subject_max_score integer := 0;
  v_subject_correct_answers integer := 0;
  v_topic_max_score integer := 0;
  v_played_day date;
  v_rows integer := 0;
begin
  if v_teacher_id is null then
    raise exception 'No hay sesión activa.';
  end if;

  if p_status not in ('approved', 'rejected', 'needs_changes') then
    raise exception 'El estado de revisión no es válido.';
  end if;

  select *
  into v_attempt
  from public.attempt_history
  where id = p_attempt_history_id
  for update;

  if not found then
    raise exception 'Intento no encontrado.';
  end if;

  select *
  into v_question
  from public.questions
  where id = v_attempt.question_id;

  if not found or v_question.type <> 'open_answer' then
    raise exception 'Solo se pueden revisar respuestas abiertas.';
  end if;

  if not exists (
    select 1
    from public.subjects
    where subjects.id = v_question.subject_id
      and (
        subjects.teacher_id = v_teacher_id
        or v_attempt.manual_review_assigned_to = v_teacher_id
        or public.is_admin()
      )
  ) then
    raise exception 'No puedes revisar respuestas de este curso.';
  end if;

  if v_attempt.manual_review_status = 'not_required' then
    raise exception 'Esta respuesta no requiere revisión manual.';
  end if;

  v_new_is_correct := p_status = 'approved';
  v_classroom_id := coalesce(v_question.classroom_id, public.ensure_default_classroom(v_question.subject_id));
  v_played_day := (coalesce(v_attempt.attempted_at, now()) at time zone 'Europe/Madrid')::date;
  v_new_earned_points := case when v_new_is_correct then coalesce(v_question.points_base, 10) else 0 end;
  v_delta_points := v_new_earned_points - coalesce(v_attempt.earned_points, 0);
  v_delta_correct := case when v_new_is_correct then 1 else 0 end
    - case when coalesce(v_attempt.is_correct, false) then 1 else 0 end;
  v_student_id := v_attempt.student_id;

  update public.attempt_history
  set is_correct = v_new_is_correct,
      earned_points = v_new_earned_points,
      manual_review_status = p_status,
      reviewed_by = v_teacher_id,
      reviewed_at = now(),
      review_notes = nullif(trim(coalesce(p_notes, '')), '')
  where id = p_attempt_history_id;

  if v_attempt.attempt_id is not null then
    update public.game_attempts
    set total_score = greatest(0, coalesce(total_score, 0) + v_delta_points),
        correct_answers = greatest(0, coalesce(correct_answers, 0) + v_delta_correct),
        updated_at = now()
    where id = v_attempt.attempt_id;
  end if;

  select greatest(
    coalesce((
      select max(coalesce(ga.total_score, 0))::integer
      from public.game_attempts ga
      where ga.student_id = v_attempt.student_id
        and ga.subject_id = v_question.subject_id
        and coalesce(ga.classroom_id, v_classroom_id) = v_classroom_id
    ), 0),
    coalesce((
      select max(coalesce(ah.earned_points, 0))::integer
      from public.attempt_history ah
      join public.questions q on q.id = ah.question_id
      where ah.student_id = v_attempt.student_id
        and q.subject_id = v_question.subject_id
        and coalesce(q.classroom_id, public.ensure_default_classroom(q.subject_id)) = v_classroom_id
    ), 0)
  )
  into v_subject_max_score;

  select count(*) filter (where coalesce(ah.is_correct, false))::integer
  into v_subject_correct_answers
  from public.attempt_history ah
  join public.questions q on q.id = ah.question_id
  where ah.student_id = v_attempt.student_id
    and q.subject_id = v_question.subject_id
    and coalesce(q.classroom_id, public.ensure_default_classroom(q.subject_id)) = v_classroom_id;

  update public.subject_scores
  set max_score = v_subject_max_score,
      correct_answers = v_subject_correct_answers,
      played_days = (
        select array_agg(distinct day order by day)
        from unnest(array_append(coalesce(played_days, '{}'::date[]), v_played_day)) as day
      ),
      played_at = greatest(coalesce(played_at, 'epoch'::timestamptz), coalesce(v_attempt.attempted_at, now())),
      updated_at = now(),
      subject_id = v_question.subject_id
  where student_id = v_attempt.student_id
    and classroom_id = v_classroom_id;

  get diagnostics v_rows = row_count;

  if v_rows = 0 then
    insert into public.subject_scores (
      student_id, subject_id, classroom_id, max_score, correct_answers,
      played_days, played_at, updated_at
    ) values (
      v_attempt.student_id, v_question.subject_id, v_classroom_id,
      v_subject_max_score, v_subject_correct_answers, array[v_played_day],
      coalesce(v_attempt.attempted_at, now()), now()
    );
  end if;

  if v_question.topic_id is not null then
    select greatest(
      coalesce((
        select max(coalesce(ga.total_score, 0))::integer
        from public.game_attempts ga
        where ga.student_id = v_attempt.student_id
          and ga.subject_id = v_question.subject_id
          and ga.topic_id = v_question.topic_id
          and coalesce(ga.classroom_id, v_classroom_id) = v_classroom_id
      ), 0),
      coalesce((
        select max(coalesce(ah.earned_points, 0))::integer
        from public.attempt_history ah
        join public.questions q on q.id = ah.question_id
        where ah.student_id = v_attempt.student_id
          and q.subject_id = v_question.subject_id
          and q.topic_id = v_question.topic_id
          and coalesce(q.classroom_id, public.ensure_default_classroom(q.subject_id)) = v_classroom_id
      ), 0)
    )
    into v_topic_max_score;

    update public.topic_scores
    set max_score = v_topic_max_score,
        played_at = greatest(coalesce(played_at, 'epoch'::timestamptz), coalesce(v_attempt.attempted_at, now())),
        updated_at = now(),
        classroom_id = v_classroom_id,
        subject_id = v_question.subject_id
    where student_id = v_attempt.student_id
      and topic_id = v_question.topic_id;

    get diagnostics v_rows = row_count;

    if v_rows = 0 then
      insert into public.topic_scores (
        student_id, subject_id, classroom_id, topic_id, max_score,
        played_at, updated_at
      ) values (
        v_attempt.student_id, v_question.subject_id, v_classroom_id,
        v_question.topic_id, v_topic_max_score,
        coalesce(v_attempt.attempted_at, now()), now()
      );
    end if;
  end if;

  perform public.recalculate_student_points(v_attempt.student_id);

  if nullif(trim(coalesce(p_notes, '')), '') is not null then
    perform public.add_manual_review_comment(
      p_attempt_history_id,
      p_notes,
      p_comment_audience
    );
  end if;

  perform public.create_notification(
    v_student_id,
    'student',
    'manual_review',
    case
      when p_status = 'approved' then 'Respuesta abierta aprobada'
      when p_status = 'rejected' then 'Respuesta abierta revisada'
      else 'Tu respuesta necesita cambios'
    end,
    case
      when p_status = 'approved' then concat('Has obtenido ', v_new_earned_points, ' XP.')
      when p_status = 'rejected' then 'El profesor ha revisado tu respuesta. Consulta el comentario para mejorar.'
      else 'El profesor ha dejado indicaciones para que revises el contenido.'
    end,
    case when p_status = 'approved' then 'checkmark-circle-outline' else 'create-outline' end,
    case when p_status = 'approved' then '#34D399' else '#F59E0B' end,
    '/(student)/activity-log',
    'attempt_history',
    p_attempt_history_id::text,
    jsonb_build_object(
      'attempt_history_id', p_attempt_history_id,
      'manual_review_status', p_status,
      'earned_points', v_new_earned_points
    ),
    concat('manual-review-status:', p_attempt_history_id, ':', p_status)
  );

  return jsonb_build_object(
    'id', p_attempt_history_id,
    'is_correct', v_new_is_correct,
    'earned_points', v_new_earned_points,
    'manual_review_status', p_status,
    'subject_max_score', v_subject_max_score,
    'subject_correct_answers', v_subject_correct_answers,
    'topic_max_score', case when v_question.topic_id is null then null else v_topic_max_score end
  );
end;
$$;

create or replace function public.review_manual_review_attempt(
  p_attempt_history_id bigint,
  p_status text,
  p_notes text default null,
  p_comment_audience text default 'student',
  p_rubric_id uuid default null,
  p_rubric_result jsonb default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_previous_status text; v_result jsonb; v_owner uuid; v_assignee uuid;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select ah.manual_review_status, s.teacher_id, ah.manual_review_assigned_to
  into v_previous_status, v_owner, v_assignee
  from public.attempt_history ah join public.questions q on q.id = ah.question_id join public.subjects s on s.id = q.subject_id
  where ah.id = p_attempt_history_id for update of ah;
  if not found then raise exception 'Review not found'; end if;
  if not public.is_admin() and v_owner <> v_user_id and v_assignee is distinct from v_user_id then raise exception 'Review access denied'; end if;
  if p_rubric_id is not null and not exists (select 1 from public.manual_review_rubrics where id = p_rubric_id and teacher_id = v_user_id and active) then raise exception 'Invalid rubric'; end if;

  if v_previous_status is distinct from p_status then
    select public.review_open_answer_attempt_assigned(p_attempt_history_id, p_status, p_notes, p_comment_audience) into v_result;
  else
    if nullif(trim(coalesce(p_notes, '')), '') is not null then
      perform public.add_manual_review_comment(p_attempt_history_id, p_notes, p_comment_audience);
    end if;
    select jsonb_build_object('id', ah.id, 'manual_review_status', ah.manual_review_status, 'earned_points', ah.earned_points)
    into v_result from public.attempt_history ah where ah.id = p_attempt_history_id;
  end if;

  update public.attempt_history
  set manual_review_rubric_id = p_rubric_id,
      manual_review_rubric_result = case when p_rubric_id is null then null else coalesce(p_rubric_result, '{}'::jsonb) end,
      manual_review_assigned_to = coalesce(manual_review_assigned_to, v_user_id)
  where id = p_attempt_history_id;
  return coalesce(v_result, '{}'::jsonb) || jsonb_build_object('statusChanged', v_previous_status is distinct from p_status);
end;
$$;

create or replace function public.batch_review_manual_attempts(
  p_attempt_ids bigint[], p_status text, p_notes text default null, p_comment_audience text default 'student', p_rubric_id uuid default null, p_rubric_result jsonb default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_id bigint; v_succeeded integer := 0; v_failed integer := 0; v_errors jsonb := '[]'::jsonb;
begin
  foreach v_id in array coalesce(p_attempt_ids, '{}'::bigint[]) loop
    begin
      perform public.review_manual_review_attempt(v_id, p_status, p_notes, p_comment_audience, p_rubric_id, p_rubric_result);
      v_succeeded := v_succeeded + 1;
    exception when others then
      v_failed := v_failed + 1;
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('id', v_id, 'error', left(sqlerrm, 180)));
    end;
  end loop;
  return jsonb_build_object('succeeded', v_succeeded, 'failed', v_failed, 'errors', v_errors);
end;
$$;

create or replace function public.get_manual_review_history(p_attempt_history_id bigint)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_result jsonb;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if not exists (
    select 1 from public.attempt_history ah join public.questions q on q.id = ah.question_id join public.subjects s on s.id = q.subject_id
    where ah.id = p_attempt_history_id and (public.is_admin() or s.teacher_id = v_user_id or ah.manual_review_assigned_to = v_user_id)
  ) then raise exception 'Review access denied'; end if;
  select coalesce(jsonb_agg(jsonb_build_object('id', h.id, 'eventType', h.event_type, 'fromStatus', h.from_status, 'toStatus', h.to_status, 'actorName', coalesce(p.alias, 'Sistema'), 'before', h.before_state, 'after', h.after_state, 'createdAt', h.created_at) order by h.created_at desc, h.id desc), '[]'::jsonb)
  into v_result from public.manual_review_history h left join public.profiles p on p.id = h.actor_id where h.attempt_history_id = p_attempt_history_id;
  return v_result;
end;
$$;

create or replace function public.get_teacher_question_report(
  p_question_id bigint,
  p_classroom_id bigint default null,
  p_date_from timestamptz default null,
  p_date_to timestamptz default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_subject_id bigint; v_result jsonb;
begin
  select q.subject_id into v_subject_id
  from public.questions q join public.subjects s on s.id = q.subject_id
  where q.id = p_question_id and (public.is_admin() or s.teacher_id = v_user_id);
  if not found then raise exception 'Question report access denied'; end if;

  with attempts as (
    select ah.*, coalesce(ga.classroom_id, q.classroom_id) as resolved_classroom_id
    from public.attempt_history ah
    join public.questions q on q.id = ah.question_id
    left join public.game_attempts ga on ga.id = ah.attempt_id
    where ah.question_id = p_question_id
      and (p_classroom_id is null or coalesce(ga.classroom_id, q.classroom_id) = p_classroom_id)
      and (p_date_from is null or ah.attempted_at >= p_date_from)
      and (p_date_to is null or ah.attempted_at < p_date_to)
  ), summary as (
    select count(*)::integer total_attempts,
      count(*) filter (where is_correct)::integer correct_attempts,
      count(*) filter (where not is_correct)::integer failed_attempts,
      count(*) filter (where was_skipped)::integer skipped_attempts,
      count(distinct student_id)::integer sample_size,
      round(avg(time_taken_seconds) filter (where time_taken_seconds is not null), 1) average_time_seconds,
      round(100.0 * count(*) filter (where was_skipped) / nullif(count(*), 0), 1) abandonment_percent
    from attempts
  ), answer_distribution as (
    select coalesce(a.text, case when at.was_skipped then 'Omitida' when q.type = 'open_answer' then 'Respuesta libre' else 'Respuesta interactiva' end) label,
      count(*)::integer count,
      bool_or(coalesce(a.is_correct, at.is_correct)) correct
    from attempts at join public.questions q on q.id = at.question_id left join public.answers a on a.id = at.answer_id
    group by 1
  ), class_comparison as (
    select coalesce(at.resolved_classroom_id, 0) classroom_id, coalesce(c.name, 'Sin clase') classroom_name,
      count(*)::integer attempts, count(*) filter (where at.is_correct)::integer correct,
      round(100.0 * count(*) filter (where not at.is_correct) / nullif(count(*), 0), 1) failure_percent,
      round(avg(at.time_taken_seconds) filter (where at.time_taken_seconds is not null), 1) average_time_seconds
    from attempts at left join public.classrooms c on c.id = at.resolved_classroom_id group by 1, 2
  ), temporal as (
    select date_trunc('day', attempted_at)::date as "day", count(*)::integer attempts,
      round(100.0 * count(*) filter (where not is_correct) / nullif(count(*), 0), 1) failure_percent,
      round(avg(time_taken_seconds) filter (where time_taken_seconds is not null), 1) average_time_seconds
    from attempts where attempted_at >= now() - interval '30 days' group by 1 order by 1
  ), subject_student_scores as (
    select ah.student_id, avg(case when ah.is_correct then 1.0 else 0.0 end) subject_accuracy
    from public.attempt_history ah join public.questions q on q.id = ah.question_id
    where q.subject_id = v_subject_id group by ah.student_id
  ), ranked as (
    select student_id, subject_accuracy, percent_rank() over(order by subject_accuracy) pr from subject_student_scores
  ), discrimination as (
    select round(
      (avg(case when a.is_correct then 1.0 else 0.0 end) filter (where r.pr >= 0.73)
       - avg(case when a.is_correct then 1.0 else 0.0 end) filter (where r.pr <= 0.27))::numeric, 3
    ) value
    from attempts a join ranked r on r.student_id = a.student_id
  ), recent as (
    select
      round(100.0 * count(*) filter (where not is_correct and attempted_at >= now() - interval '7 days') / nullif(count(*) filter (where attempted_at >= now() - interval '7 days'), 0), 1) current_failure,
      round(100.0 * count(*) filter (where not is_correct and attempted_at >= now() - interval '14 days' and attempted_at < now() - interval '7 days') / nullif(count(*) filter (where attempted_at >= now() - interval '14 days' and attempted_at < now() - interval '7 days'), 0), 1) previous_failure
    from attempts
  )
  select jsonb_build_object(
    'question', (select jsonb_build_object('id', q.id, 'text', q.text, 'type', q.type, 'subjectId', q.subject_id, 'classroomId', q.classroom_id, 'topicId', q.topic_id, 'explanation', q.explanation, 'mediaType', q.media_type, 'mediaPath', q.media_path, 'mediaAltText', q.media_alt_text, 'mediaCaption', q.media_caption, 'pointsBase', q.points_base, 'timeLimitSeconds', q.time_limit_seconds, 'difficulty', q.difficulty, 'active', q.active, 'subjectName', s.name, 'classroomName', c.name, 'topicName', st.title) from public.questions q join public.subjects s on s.id = q.subject_id left join public.classrooms c on c.id = q.classroom_id left join public.subject_topics st on st.id = q.topic_id where q.id = p_question_id),
    'summary', (select jsonb_build_object('totalAttempts', coalesce(total_attempts,0), 'correctAttempts', coalesce(correct_attempts,0), 'failedAttempts', coalesce(failed_attempts,0), 'sampleSize', coalesce(sample_size,0), 'lowSample', coalesce(sample_size,0) < 10, 'abandonmentPercent', coalesce(abandonment_percent,0), 'averageTimeSeconds', average_time_seconds, 'discrimination', (select value from discrimination), 'failureTrendPoints', coalesce((select current_failure - previous_failure from recent),0)) from summary),
    'answerDistribution', coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', count, 'correct', correct, 'percent', round(100.0 * count / nullif((select total_attempts from summary),0),1)) order by count desc) from answer_distribution), '[]'::jsonb),
    'classComparison', coalesce((select jsonb_agg(to_jsonb(class_comparison) order by failure_percent desc) from class_comparison), '[]'::jsonb),
    'temporalTrend', coalesce((select jsonb_agg(to_jsonb(temporal) order by temporal."day") from temporal), '[]'::jsonb),
    'classOptions', coalesce((select jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name) order by c.name) from public.classrooms c where c.subject_id = v_subject_id and c.active), '[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.get_teacher_question_affected_students_page(
  p_question_id bigint, p_classroom_id bigint default null, p_date_from timestamptz default null, p_date_to timestamptz default null, p_limit integer default 20, p_offset integer default 0
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_limit integer := least(greatest(coalesce(p_limit,20),1),100); v_offset integer := greatest(coalesce(p_offset,0),0); v_result jsonb;
begin
  if not exists (select 1 from public.questions q join public.subjects s on s.id = q.subject_id where q.id = p_question_id and (public.is_admin() or s.teacher_id = v_user_id)) then raise exception 'Question report access denied'; end if;
  with attempts as (
    select ah.*, coalesce(ga.classroom_id, q.classroom_id) resolved_classroom_id
    from public.attempt_history ah join public.questions q on q.id = ah.question_id left join public.game_attempts ga on ga.id = ah.attempt_id
    where ah.question_id = p_question_id and not ah.is_correct
      and (p_classroom_id is null or coalesce(ga.classroom_id, q.classroom_id) = p_classroom_id)
      and (p_date_from is null or ah.attempted_at >= p_date_from) and (p_date_to is null or ah.attempted_at < p_date_to)
  ), grouped as (
    select a.student_id, coalesce(p.alias, 'Alumno') alias, count(*)::integer failures,
      count(*)::integer attempts, round(avg(a.time_taken_seconds) filter(where a.time_taken_seconds is not null),1) average_time_seconds,
      max(a.attempted_at) last_attempt_at, coalesce(max(c.name), 'Sin clase') classroom_name
    from attempts a left join public.profiles p on p.id = a.student_id left join public.classrooms c on c.id = a.resolved_classroom_id
    group by a.student_id, p.alias
  ), page as (select * from grouped order by failures desc, last_attempt_at desc nulls last limit v_limit offset v_offset)
  select jsonb_build_object('items', coalesce((select jsonb_agg(to_jsonb(page) order by failures desc, last_attempt_at desc nulls last) from page), '[]'::jsonb), 'total', (select count(*) from grouped)) into v_result;
  return v_result;
end;
$$;

alter table public.teacher_audit_logs
  add column if not exists before_state jsonb not null default '{}'::jsonb,
  add column if not exists after_state jsonb not null default '{}'::jsonb,
  add column if not exists severity text not null default 'info' check (severity in ('info','warning','critical')),
  add column if not exists request_id uuid;

create table if not exists public.teacher_audit_retention_policy (
  singleton boolean primary key default true check (singleton),
  retention_days integer not null default 730 check (retention_days between 90 and 3650),
  updated_at timestamptz not null default now()
);
insert into public.teacher_audit_retention_policy(singleton) values (true) on conflict (singleton) do nothing;

alter table public.teacher_audit_retention_policy enable row level security;
revoke all on public.teacher_audit_retention_policy from public, anon, authenticated;

create table if not exists public.teacher_audit_saved_filters (
  id uuid primary key default gen_random_uuid(), teacher_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 80), filters jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(teacher_id, name)
);

create table if not exists public.teacher_audit_alerts (
  id bigint generated by default as identity primary key, teacher_id uuid not null references public.profiles(id) on delete cascade,
  pattern_key text not null, severity text not null check (severity in ('warning','critical')), title text not null, description text not null,
  window_started_at timestamptz not null, window_ended_at timestamptz not null, event_count integer not null,
  acknowledged_at timestamptz, created_at timestamptz not null default now(), unique(teacher_id, pattern_key, window_started_at)
);

create table if not exists public.teacher_audit_export_requests (
  id uuid primary key default gen_random_uuid(), teacher_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'queued' check(status in ('queued','processing','ready','failed','expired')),
  filters jsonb not null default '{}'::jsonb, object_path text, row_count integer, requested_at timestamptz not null default now(),
  started_at timestamptz, completed_at timestamptz, expires_at timestamptz, error_message text, updated_at timestamptz not null default now()
);
create index if not exists teacher_audit_export_requests_queue_idx on public.teacher_audit_export_requests(status, requested_at);
create unique index if not exists teacher_audit_export_requests_one_active_idx
  on public.teacher_audit_export_requests(teacher_id)
  where status in ('queued','processing');

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('teacher-audit-exports','teacher-audit-exports',false,52428800,array['text/csv']::text[])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

alter table public.teacher_audit_saved_filters enable row level security;
alter table public.teacher_audit_alerts enable row level security;
alter table public.teacher_audit_export_requests enable row level security;
revoke all on public.teacher_audit_saved_filters, public.teacher_audit_alerts, public.teacher_audit_export_requests from public, anon, authenticated;
grant select on public.teacher_audit_saved_filters, public.teacher_audit_alerts, public.teacher_audit_export_requests to authenticated;

drop policy if exists "teacher_audit_saved_filters_select_own" on public.teacher_audit_saved_filters;
create policy "teacher_audit_saved_filters_select_own" on public.teacher_audit_saved_filters for select to authenticated using (teacher_id=auth.uid() or public.is_admin());
drop policy if exists "teacher_audit_alerts_select_own" on public.teacher_audit_alerts;
create policy "teacher_audit_alerts_select_own" on public.teacher_audit_alerts for select to authenticated using (teacher_id=auth.uid() or public.is_admin());
drop policy if exists "teacher_audit_exports_select_own" on public.teacher_audit_export_requests;
create policy "teacher_audit_exports_select_own" on public.teacher_audit_export_requests for select to authenticated using (teacher_id=auth.uid() or public.is_admin());
drop policy if exists "teacher_audit_export_objects_select_own" on storage.objects;
create policy "teacher_audit_export_objects_select_own" on storage.objects for select to authenticated using (bucket_id='teacher-audit-exports' and (storage.foldername(name))[1]=auth.uid()::text);

create or replace function public.sanitize_teacher_audit_payload(p_value jsonb)
returns jsonb
language plpgsql
immutable
set search_path = public
as $$
declare
  v_result jsonb;
begin
  if p_value is null then return '{}'::jsonb; end if;

  if jsonb_typeof(p_value) = 'object' then
    select coalesce(jsonb_object_agg(entry.key, public.sanitize_teacher_audit_payload(entry.value)), '{}'::jsonb)
    into v_result
    from jsonb_each(p_value) entry
    where lower(entry.key) not in (
      'password','password_hash','current_password','new_password','token','access_token','refresh_token',
      'secret','service_role','authorization','email','phone','submitted_answer_text',
      'submitted_answer_payload','answer','body','message','content','ip_address','user_agent'
    );
    return v_result;
  end if;

  if jsonb_typeof(p_value) = 'array' then
    select coalesce(jsonb_agg(public.sanitize_teacher_audit_payload(item.value)), '[]'::jsonb)
    into v_result
    from jsonb_array_elements(p_value) item;
    return v_result;
  end if;

  return p_value;
end;
$$;

create or replace function public.prepare_teacher_audit_log()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.before_state := public.sanitize_teacher_audit_payload(
    coalesce(nullif(new.before_state, '{}'::jsonb), new.metadata -> 'before', new.metadata -> 'old', '{}'::jsonb)
  );
  new.after_state := public.sanitize_teacher_audit_payload(
    coalesce(nullif(new.after_state, '{}'::jsonb), new.metadata -> 'after', new.metadata -> 'new', '{}'::jsonb)
  );
  new.metadata := public.sanitize_teacher_audit_payload(
    coalesce(new.metadata, '{}'::jsonb) - array['before','after','old','new']
  );

  if coalesce(new.severity, 'info') = 'info'
     and (new.action ilike '%delete%' or new.action ilike '%archive%' or new.action ilike '%deactivate%' or new.action ilike '%reset%') then
    new.severity := 'warning';
  end if;
  return new;
end;
$$;
drop trigger if exists prepare_teacher_audit_log_trigger on public.teacher_audit_logs;
create trigger prepare_teacher_audit_log_trigger before insert on public.teacher_audit_logs for each row execute function public.prepare_teacher_audit_log();

create or replace function public.prevent_teacher_audit_mutation()
returns trigger language plpgsql set search_path=public as $$
begin
  if tg_op='DELETE' and current_setting('omniquest.audit_retention', true)='on' then return old; end if;
  raise exception 'Teacher audit logs are immutable';
end;
$$;
drop trigger if exists prevent_teacher_audit_mutation_trigger on public.teacher_audit_logs;
create trigger prevent_teacher_audit_mutation_trigger before update or delete on public.teacher_audit_logs for each row execute function public.prevent_teacher_audit_mutation();

create or replace function public.apply_teacher_audit_retention()
returns integer language plpgsql security definer set search_path=public as $$
declare v_days integer; v_count integer;
begin
  select retention_days into v_days from public.teacher_audit_retention_policy where singleton=true;
  perform set_config('omniquest.audit_retention','on',true);
  delete from public.teacher_audit_logs where created_at < now() - make_interval(days=>coalesce(v_days,730));
  get diagnostics v_count=row_count;
  return v_count;
end;
$$;

create or replace function public.detect_teacher_audit_anomalies()
returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer := 0; v_added integer := 0;
begin
  insert into public.teacher_audit_alerts(teacher_id,pattern_key,severity,title,description,window_started_at,window_ended_at,event_count)
  select teacher_id,'destructive-burst','critical','Patrón destructivo inusual',format('%s acciones destructivas en 15 minutos.',count(*)),date_trunc('minute',now()-interval '15 minutes'),date_trunc('minute',now()),count(*)::integer
  from public.teacher_audit_logs where created_at>=now()-interval '15 minutes' and (action ilike '%delete%' or action ilike '%archive%' or action ilike '%deactivate%' or severity='critical')
  group by teacher_id having count(*)>=8
  on conflict do nothing;
  get diagnostics v_added=row_count;
  v_count := v_count + v_added;

  insert into public.teacher_audit_alerts(teacher_id,pattern_key,severity,title,description,window_started_at,window_ended_at,event_count)
  select teacher_id,'code-burst','warning','Generación elevada de códigos',format('%s acciones sobre códigos en una hora.',count(*)),date_trunc('hour',now()-interval '1 hour'),date_trunc('hour',now()),count(*)::integer
  from public.teacher_audit_logs where created_at>=now()-interval '1 hour' and (action ilike '%code%' or target_table='classrooms')
  group by teacher_id having count(*)>=20
  on conflict do nothing;
  get diagnostics v_added=row_count;
  v_count := v_count + v_added;
  return v_count;
end;
$$;

create or replace function public.get_teacher_audit_logs_page_v2(
  p_category text default 'all', p_search text default null, p_action text default null, p_target_table text default null,
  p_severity text default null, p_from timestamptz default null, p_to timestamptz default null, p_limit integer default 25, p_offset integer default 0
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user_id uuid:=auth.uid(); v_limit integer:=least(greatest(coalesce(p_limit,25),1),100); v_offset integer:=greatest(coalesce(p_offset,0),0); v_result jsonb;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  with filtered as (
    select l.* from public.teacher_audit_logs l where (public.is_admin() or l.teacher_id=v_user_id)
      and (coalesce(nullif(p_category,''),'all')='all'
        or (p_category='student' and (l.target_table in ('profiles','enrollments','subject_scores','topic_scores') or l.action ilike '%student%'))
        or (p_category='question' and (l.target_table in ('questions','answers') or l.action ilike '%question%'))
        or (p_category='subject' and (l.target_table in ('subjects','subject_topics') or l.action ilike any(array['%subject%','%course%','%topic%'])))
        or (p_category='code' and (l.action ilike '%code%' or l.target_table='classrooms'))
        or (p_category='profile' and (l.action ilike '%profile%' or l.target_table='profiles')))
      and (nullif(trim(coalesce(p_search,'')),'') is null or concat_ws(' ',l.action,l.target_table,l.target_id,l.metadata::text) ilike '%'||trim(p_search)||'%')
      and (nullif(trim(coalesce(p_action,'')),'') is null or l.action=p_action)
      and (nullif(trim(coalesce(p_target_table,'')),'') is null or l.target_table=p_target_table)
      and (nullif(trim(coalesce(p_severity,'')),'') is null or l.severity=p_severity)
      and (p_from is null or l.created_at>=p_from) and (p_to is null or l.created_at<p_to)
  ), page as (select * from filtered order by created_at desc,id desc limit v_limit offset v_offset)
  select jsonb_build_object(
    'items',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'teacher_id',p.teacher_id,'action',p.action,'target_table',p.target_table,'target_id',p.target_id,'metadata',p.metadata,'before_state',p.before_state,'after_state',p.after_state,'severity',p.severity,'request_id',p.request_id,'created_at',p.created_at) order by p.created_at desc,p.id desc) from page p),'[]'::jsonb),
    'total',(select count(*) from filtered),
    'stats',jsonb_build_object('last7Days',(select count(*) from filtered where created_at>=now()-interval '7 days'),'critical',(select count(*) from filtered where severity='critical'),'warning',(select count(*) from filtered where severity='warning')),
    'actions',coalesce((select jsonb_agg(distinct action) from filtered),'[]'::jsonb),
    'targetTables',coalesce((select jsonb_agg(distinct target_table) from filtered where target_table is not null),'[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.get_teacher_audit_configuration()
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user_id uuid:=auth.uid(); v_result jsonb;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select jsonb_build_object(
    'retentionDays',(select retention_days from public.teacher_audit_retention_policy where singleton=true),
    'savedFilters',coalesce((select jsonb_agg(to_jsonb(f) order by f.updated_at desc) from public.teacher_audit_saved_filters f where f.teacher_id=v_user_id),'[]'::jsonb),
    'alerts',coalesce((select jsonb_agg(to_jsonb(a) order by a.created_at desc) from (select * from public.teacher_audit_alerts where teacher_id=v_user_id and acknowledged_at is null order by created_at desc limit 20) a),'[]'::jsonb),
    'exports',coalesce((select jsonb_agg(to_jsonb(e) order by e.requested_at desc) from (select * from public.teacher_audit_export_requests where teacher_id=v_user_id order by requested_at desc limit 10) e),'[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.save_teacher_audit_filter(p_id uuid,p_name text,p_filters jsonb)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_user_id uuid:=auth.uid(); v_id uuid;
begin
  if p_id is null then insert into public.teacher_audit_saved_filters(teacher_id,name,filters) values(v_user_id,trim(p_name),p_filters) on conflict(teacher_id,name) do update set filters=excluded.filters,updated_at=now() returning id into v_id;
  else update public.teacher_audit_saved_filters set name=trim(p_name),filters=p_filters,updated_at=now() where id=p_id and teacher_id=v_user_id returning id into v_id; end if;
  if v_id is null then raise exception 'Filter not found'; end if; return v_id;
end;
$$;

create or replace function public.acknowledge_teacher_audit_alert(p_alert_id bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin update public.teacher_audit_alerts set acknowledged_at=now() where id=p_alert_id and teacher_id=auth.uid() and acknowledged_at is null; return found; end;
$$;

create or replace function public.request_teacher_audit_export(p_filters jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user_id uuid:=auth.uid(); v_request public.teacher_audit_export_requests%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if jsonb_typeof(coalesce(p_filters, '{}'::jsonb)) <> 'object' then raise exception 'Invalid export filters'; end if;

  update public.teacher_audit_export_requests
  set status='expired', updated_at=now()
  where teacher_id=v_user_id and status='ready' and expires_at <= now();

  select * into v_request
  from public.teacher_audit_export_requests
  where teacher_id=v_user_id and status in ('queued','processing')
  order by requested_at desc limit 1;

  if not found then
    insert into public.teacher_audit_export_requests(teacher_id,filters)
    values(v_user_id,coalesce(p_filters,'{}'::jsonb))
    on conflict (teacher_id) where status in ('queued','processing') do nothing
    returning * into v_request;

    if v_request.id is null then
      select * into v_request
      from public.teacher_audit_export_requests
      where teacher_id=v_user_id and status in ('queued','processing')
      order by requested_at desc limit 1;
    end if;
  end if;

  return jsonb_build_object('id',v_request.id,'status',v_request.status,'requestedAt',v_request.requested_at);
end;
$$;

create or replace function public.claim_teacher_audit_export_requests(p_limit integer default 3)
returns setof public.teacher_audit_export_requests language plpgsql security definer set search_path=public as $$
begin
  return query with candidates as (
    select id from public.teacher_audit_export_requests where status='queued' order by requested_at for update skip locked limit least(greatest(coalesce(p_limit,3),1),10)
  ) update public.teacher_audit_export_requests r set status='processing',started_at=now(),updated_at=now() from candidates c where r.id=c.id returning r.*;
end;
$$;

create or replace function public.complete_teacher_audit_export(p_request_id uuid,p_status text,p_object_path text default null,p_row_count integer default null,p_error_message text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.teacher_audit_export_requests set status=p_status,object_path=p_object_path,row_count=p_row_count,error_message=left(p_error_message,500),completed_at=now(),expires_at=case when p_status='ready' then now()+interval '7 days' else null end,updated_at=now() where id=p_request_id;
end;
$$;

do $$ begin
  if exists(select 1 from pg_extension where extname='pg_cron') then
    if exists(select 1 from cron.job where jobname='omniquest-teacher-audit-retention') then perform cron.unschedule((select jobid from cron.job where jobname='omniquest-teacher-audit-retention' limit 1)); end if;
    perform cron.schedule('omniquest-teacher-audit-retention','35 3 * * *','select public.apply_teacher_audit_retention();');
    if exists(select 1 from cron.job where jobname='omniquest-teacher-audit-anomalies') then perform cron.unschedule((select jobid from cron.job where jobname='omniquest-teacher-audit-anomalies' limit 1)); end if;
    perform cron.schedule('omniquest-teacher-audit-anomalies','*/15 * * * *','select public.detect_teacher_audit_anomalies();');
  end if;
end $$;

revoke all on function public.get_manual_review_configuration() from public,anon;
revoke all on function public.save_manual_review_settings(integer) from public,anon;
revoke all on function public.save_manual_review_rubric(uuid,text,bigint,jsonb) from public,anon;
revoke all on function public.save_manual_review_template(uuid,text,text,text) from public,anon;
revoke all on function public.save_manual_review_filter(uuid,text,jsonb) from public,anon;
revoke all on function public.assign_manual_review_attempts(bigint[],uuid) from public,anon;
revoke all on function public.review_open_answer_attempt_assigned(bigint,text,text,text) from public,anon,authenticated;
revoke all on function public.review_manual_review_attempt(bigint,text,text,text,uuid,jsonb) from public,anon;
revoke all on function public.batch_review_manual_attempts(bigint[],text,text,text,uuid,jsonb) from public,anon;
revoke all on function public.get_manual_review_history(bigint) from public,anon;
revoke all on function public.get_teacher_question_report(bigint,bigint,timestamptz,timestamptz) from public,anon;
revoke all on function public.get_teacher_question_affected_students_page(bigint,bigint,timestamptz,timestamptz,integer,integer) from public,anon;
revoke all on function public.get_teacher_audit_logs_page_v2(text,text,text,text,text,timestamptz,timestamptz,integer,integer) from public,anon;
revoke all on function public.get_teacher_audit_configuration() from public,anon;
revoke all on function public.save_teacher_audit_filter(uuid,text,jsonb) from public,anon;
revoke all on function public.acknowledge_teacher_audit_alert(bigint) from public,anon;
revoke all on function public.request_teacher_audit_export(jsonb) from public,anon;
revoke all on function public.claim_teacher_audit_export_requests(integer) from public,anon,authenticated;
revoke all on function public.complete_teacher_audit_export(uuid,text,text,integer,text) from public,anon,authenticated;

grant execute on function public.get_manual_review_configuration() to authenticated;
grant execute on function public.save_manual_review_settings(integer) to authenticated;
grant execute on function public.save_manual_review_rubric(uuid,text,bigint,jsonb) to authenticated;
grant execute on function public.save_manual_review_template(uuid,text,text,text) to authenticated;
grant execute on function public.save_manual_review_filter(uuid,text,jsonb) to authenticated;
grant execute on function public.assign_manual_review_attempts(bigint[],uuid) to authenticated;
grant execute on function public.review_manual_review_attempt(bigint,text,text,text,uuid,jsonb) to authenticated;
grant execute on function public.batch_review_manual_attempts(bigint[],text,text,text,uuid,jsonb) to authenticated;
grant execute on function public.get_manual_review_history(bigint) to authenticated;
grant execute on function public.get_teacher_question_report(bigint,bigint,timestamptz,timestamptz) to authenticated;
grant execute on function public.get_teacher_question_affected_students_page(bigint,bigint,timestamptz,timestamptz,integer,integer) to authenticated;
grant execute on function public.get_teacher_audit_logs_page_v2(text,text,text,text,text,timestamptz,timestamptz,integer,integer) to authenticated;
grant execute on function public.get_teacher_audit_configuration() to authenticated;
grant execute on function public.save_teacher_audit_filter(uuid,text,jsonb) to authenticated;
grant execute on function public.acknowledge_teacher_audit_alert(bigint) to authenticated;
grant execute on function public.request_teacher_audit_export(jsonb) to authenticated;
grant execute on function public.claim_teacher_audit_export_requests(integer) to service_role;
grant execute on function public.complete_teacher_audit_export(uuid,text,text,integer,text) to service_role;

notify pgrst, 'reload schema';