-- Real push notification device registration.
-- Delivery is performed by Edge Functions with the service role; users can only manage their own tokens.

create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  expo_push_token text not null,
  platform text not null check (platform in ('android', 'ios')),
  device_name text,
  app_version text,
  active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (expo_push_token)
);

create index if not exists push_tokens_user_active_idx
  on public.push_tokens(user_id, active, last_seen_at desc);

alter table public.push_tokens enable row level security;

drop policy if exists "push_tokens_select_own" on public.push_tokens;
create policy "push_tokens_select_own"
on public.push_tokens for select to authenticated
using (user_id = auth.uid());

drop policy if exists "push_tokens_insert_own" on public.push_tokens;
create policy "push_tokens_insert_own"
on public.push_tokens for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "push_tokens_update_own" on public.push_tokens;
create policy "push_tokens_update_own"
on public.push_tokens for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "push_tokens_delete_own" on public.push_tokens;
create policy "push_tokens_delete_own"
on public.push_tokens for delete to authenticated
using (user_id = auth.uid());

revoke all on public.push_tokens from anon, authenticated;
revoke all on sequence public.push_tokens_id_seq from anon, authenticated;
grant select on public.push_tokens to authenticated;

create or replace function public.register_push_token(
  p_expo_push_token text,
  p_platform text,
  p_device_name text default null,
  p_app_version text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_id bigint;
  v_token text := trim(coalesce(p_expo_push_token, ''));
  v_platform text := lower(trim(coalesce(p_platform, '')));
begin
  if v_user_id is null then
    raise exception 'No authenticated user';
  end if;

  if length(v_token) < 20
     or length(v_token) > 255
     or not (v_token like 'ExpoPushToken[%]' or v_token like 'ExponentPushToken[%]') then
    raise exception 'Invalid Expo push token';
  end if;

  if v_platform not in ('android', 'ios') then
    raise exception 'Unsupported push platform';
  end if;

  insert into public.push_tokens (
    user_id,
    expo_push_token,
    platform,
    device_name,
    app_version,
    active,
    last_seen_at,
    updated_at
  ) values (
    v_user_id,
    v_token,
    v_platform,
    nullif(trim(coalesce(p_device_name, '')), ''),
    nullif(trim(coalesce(p_app_version, '')), ''),
    true,
    now(),
    now()
  )
  on conflict (expo_push_token) do update
  set
    user_id = excluded.user_id,
    platform = excluded.platform,
    device_name = excluded.device_name,
    app_version = excluded.app_version,
    active = true,
    last_seen_at = now(),
    updated_at = now()
  where public.push_tokens.user_id = excluded.user_id
     or public.push_tokens.active = false
  returning id into v_id;

  if v_id is null then
    raise exception 'Push token already belongs to another active user';
  end if;

  return jsonb_build_object('id', v_id, 'registered', true);
end;
$$;

create or replace function public.deactivate_push_token(
  p_expo_push_token text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_count integer;
begin
  if v_user_id is null then
    raise exception 'No authenticated user';
  end if;

  update public.push_tokens
  set active = false, updated_at = now()
  where user_id = v_user_id
    and (p_expo_push_token is null or expo_push_token = p_expo_push_token);

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke execute on function public.register_push_token(text, text, text, text) from public, anon;
revoke execute on function public.deactivate_push_token(text) from public, anon;
grant execute on function public.register_push_token(text, text, text, text) to authenticated;
grant execute on function public.deactivate_push_token(text) to authenticated;

comment on table public.push_tokens is 'Expo push tokens registered by authenticated devices. Service-role Edge Functions use active tokens for delivery.';
comment on function public.register_push_token(text, text, text, text) is 'Registers or refreshes the current authenticated user device token.';
comment on function public.deactivate_push_token(text) is 'Deactivates one or all push tokens belonging to the current authenticated user.';

notify pgrst, 'reload schema';
