-- Teacher topic, question authoring, student directory and student history scalability.
-- Moves expensive aggregations to PostgreSQL and exposes role-scoped paginated RPCs.

create index if not exists questions_topic_active_difficulty_created_idx
  on public.questions(topic_id, active, difficulty, created_at desc, id desc);

create index if not exists attempt_history_student_attempted_question_idx
  on public.attempt_history(student_id, attempted_at desc, question_id, id desc);

create index if not exists enrollments_student_subject_classroom_idx
  on public.enrollments(student_id, subject_id, classroom_id, joined_at);

create table if not exists public.teacher_student_notes (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete cascade,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teacher_student_notes_body_check check (char_length(trim(body)) between 1 and 2000)
);

create index if not exists teacher_student_notes_teacher_student_created_idx
  on public.teacher_student_notes(teacher_id, student_id, created_at desc, id desc);

alter table public.teacher_student_notes enable row level security;
revoke all on public.teacher_student_notes from public, anon, authenticated;
grant select, insert on public.teacher_student_notes to authenticated;

drop policy if exists "teacher_student_notes_select_owner" on public.teacher_student_notes;
create policy "teacher_student_notes_select_owner"
on public.teacher_student_notes for select to authenticated
using (teacher_id = auth.uid() or public.is_admin());

drop policy if exists "teacher_student_notes_insert_owner" on public.teacher_student_notes;
create policy "teacher_student_notes_insert_owner"
on public.teacher_student_notes for insert to authenticated
with check (
  teacher_id = auth.uid()
  and exists (
    select 1
    from public.enrollments e
    join public.subjects s on s.id = e.subject_id
    where e.student_id = teacher_student_notes.student_id
      and s.teacher_id = auth.uid()
      and (teacher_student_notes.subject_id is null or e.subject_id = teacher_student_notes.subject_id)
      and (teacher_student_notes.classroom_id is null or e.classroom_id = teacher_student_notes.classroom_id)
  )
);

create or replace function public.get_teacher_topic_summary(p_topic_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_result jsonb;
begin
  if v_teacher_id is null then
    raise exception 'Teacher session required';
  end if;

  with topic_row as (
    select
      t.id,
      t.subject_id,
      t.classroom_id,
      t.title,
      t.description,
      t.icon,
      t.sort_order,
      t.active,
      t.available_until,
      t.created_at,
      s.name as subject_name,
      s.description as subject_description,
      s.icon as subject_icon,
      s.code as subject_code,
      s.theme_color,
      c.name as classroom_name
    from public.subject_topics t
    join public.subjects s on s.id = t.subject_id
    left join public.classrooms c on c.id = t.classroom_id
    where t.id = p_topic_id
      and s.teacher_id = v_teacher_id
      and not coalesce(s.is_archived, false)
  ),
  question_stats as (
    select
      count(*)::int as questions_count,
      count(*) filter (where coalesce(q.active, true))::int as visible_questions_count,
      count(*) filter (where not coalesce(q.active, true))::int as archived_questions_count,
      coalesce(round(avg(coalesce(q.difficulty, 1))), 0)::int as average_difficulty
    from public.questions q
    join topic_row t on t.id = q.topic_id
  ),
  attempt_stats as (
    select
      count(ah.id)::int as attempts_count,
      count(distinct ah.student_id)::int as participating_students,
      coalesce(round(avg(coalesce(ah.earned_points, 0))), 0)::int as average_xp,
      max(ah.attempted_at) as last_activity_at
    from public.questions q
    join topic_row t on t.id = q.topic_id
    left join public.attempt_history ah on ah.question_id = q.id
  ),
  enrollment_stats as (
    select count(distinct e.student_id)::int as enrolled_students
    from public.enrollments e
    join topic_row t on t.subject_id = e.subject_id
    where t.classroom_id is null or e.classroom_id = t.classroom_id
  )
  select jsonb_build_object(
    'topic', jsonb_build_object(
      'id', t.id,
      'subjectId', t.subject_id,
      'classroomId', t.classroom_id,
      'title', t.title,
      'description', t.description,
      'icon', t.icon,
      'sortOrder', t.sort_order,
      'active', t.active,
      'availableUntil', t.available_until,
      'createdAt', t.created_at,
      'visibility', case when coalesce(t.active, true) then 'visible' else 'archived' end,
      'availability', case
        when not coalesce(t.active, true) then 'archived'
        when t.available_until is null then 'unlimited'
        when t.available_until <= now() then 'closed'
        else 'scheduled'
      end
    ),
    'subject', jsonb_build_object(
      'id', t.subject_id,
      'name', t.subject_name,
      'description', t.subject_description,
      'icon', t.subject_icon,
      'code', t.subject_code,
      'themeColor', t.theme_color
    ),
    'classroom', case when t.classroom_id is null then null else jsonb_build_object(
      'id', t.classroom_id,
      'name', t.classroom_name
    ) end,
    'summary', jsonb_build_object(
      'questionsCount', qs.questions_count,
      'visibleQuestionsCount', qs.visible_questions_count,
      'archivedQuestionsCount', qs.archived_questions_count,
      'averageDifficulty', qs.average_difficulty,
      'attemptsCount', ast.attempts_count,
      'averageXp', ast.average_xp,
      'enrolledStudents', es.enrolled_students,
      'participatingStudents', ast.participating_students,
      'participation', case when es.enrolled_students > 0 then round(100.0 * ast.participating_students / es.enrolled_students)::int else 0 end,
      'lastActivityAt', ast.last_activity_at
    ),
    'subjectsCount', (
      select count(*)::int
      from public.subjects s2
      where s2.teacher_id = v_teacher_id
        and not coalesce(s2.is_archived, false)
        and coalesce(s2.active, true)
    )
  ) into v_result
  from topic_row t
  cross join question_stats qs
  cross join attempt_stats ast
  cross join enrollment_stats es;

  if v_result is null then
    raise exception 'Topic not found or access denied';
  end if;

  return v_result;
end;
$$;

create or replace function public.get_teacher_topic_questions_page(
  p_topic_id bigint,
  p_difficulty integer default null,
  p_search text default null,
  p_visibility text default 'all',
  p_limit integer default 12,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 12), 1), 100);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_search text := nullif(trim(coalesce(p_search, '')), '');
  v_visibility text := lower(trim(coalesce(p_visibility, 'all')));
  v_result jsonb;
begin
  if v_teacher_id is null or not exists (
    select 1
    from public.subject_topics t
    join public.subjects s on s.id = t.subject_id
    where t.id = p_topic_id and s.teacher_id = v_teacher_id
  ) then
    raise exception 'Topic not found or access denied';
  end if;

  if v_visibility not in ('all', 'visible', 'archived') then
    raise exception 'Invalid question visibility';
  end if;

  with filtered as (
    select
      q.id,
      q.subject_id,
      q.classroom_id,
      q.topic_id,
      q.type,
      q.text,
      q.points_base,
      q.time_limit_seconds,
      q.difficulty,
      q.explanation,
      q.active,
      q.created_at,
      q.updated_at,
      q.media_type,
      q.media_path,
      coalesce(answer_stats.answers_count, 0) as answers_count,
      answer_stats.correct_answer,
      coalesce(attempt_stats.attempts_count, 0) as attempts_count,
      coalesce(attempt_stats.correct_attempts, 0) as correct_attempts
    from public.questions q
    left join lateral (
      select
        count(a.id)::int as answers_count,
        max(a.text) filter (where a.is_correct) as correct_answer
      from public.answers a
      where a.question_id = q.id
    ) answer_stats on true
    left join lateral (
      select
        count(ah.id)::int as attempts_count,
        count(ah.id) filter (where ah.is_correct)::int as correct_attempts
      from public.attempt_history ah
      where ah.question_id = q.id
    ) attempt_stats on true
    where q.topic_id = p_topic_id
      and (p_difficulty is null or q.difficulty = p_difficulty)
      and (v_search is null or q.text ilike '%' || v_search || '%')
      and (v_visibility = 'all'
        or (v_visibility = 'visible' and coalesce(q.active, true))
        or (v_visibility = 'archived' and not coalesce(q.active, true)))
  ),
  page_rows as (
    select *
    from filtered
    order by created_at desc, id desc
    limit v_limit offset v_offset
  )
  select jsonb_build_object(
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id,
        'subjectId', p.subject_id,
        'classroomId', p.classroom_id,
        'topicId', p.topic_id,
        'type', p.type,
        'text', p.text,
        'pointsBase', p.points_base,
        'timeLimitSeconds', p.time_limit_seconds,
        'difficulty', p.difficulty,
        'explanation', p.explanation,
        'active', p.active,
        'createdAt', p.created_at,
        'updatedAt', p.updated_at,
        'mediaType', p.media_type,
        'mediaPath', p.media_path,
        'answersCount', p.answers_count,
        'correctAnswer', p.correct_answer,
        'attemptsCount', p.attempts_count,
        'accuracyPercent', case when p.attempts_count > 0 then round(100.0 * p.correct_attempts / p.attempts_count)::int else null end
      ) order by p.created_at desc, p.id desc)
      from page_rows p
    ), '[]'::jsonb),
    'total', (select count(*)::int from filtered),
    'limit', v_limit,
    'offset', v_offset
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.archive_teacher_topic(p_topic_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_topic public.subject_topics%rowtype;
begin
  if v_teacher_id is null then
    raise exception 'Teacher session required';
  end if;

  update public.subject_topics t
  set active = false
  from public.subjects s
  where t.id = p_topic_id
    and s.id = t.subject_id
    and s.teacher_id = v_teacher_id
  returning t.* into v_topic;

  if not found then
    raise exception 'Topic not found or access denied';
  end if;

  update public.questions
  set active = false
  where topic_id = p_topic_id and coalesce(active, true);

  insert into public.teacher_audit_logs(teacher_id, action, target_table, target_id, metadata)
  values (
    v_teacher_id,
    'teacher.topic.archive',
    'subject_topics',
    v_topic.id::text,
    jsonb_build_object('subject_id', v_topic.subject_id, 'classroom_id', v_topic.classroom_id)
  );

  return jsonb_build_object('id', v_topic.id, 'active', false);
end;
$$;

create or replace function public.get_teacher_students_page(
  p_subject_id bigint default null,
  p_classroom_id bigint default null,
  p_status text default null,
  p_search text default null,
  p_order text default 'attention',
  p_limit integer default 20,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 100);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_search text := nullif(trim(coalesce(p_search, '')), '');
  v_status text := nullif(lower(trim(coalesce(p_status, ''))), '');
  v_order text := lower(trim(coalesce(p_order, 'attention')));
  v_result jsonb;
begin
  if v_teacher_id is null or not exists (
    select 1 from public.profiles p where p.id = v_teacher_id and p.role_id = 'teacher' and coalesce(p.active, true)
  ) then
    raise exception 'Teacher session required';
  end if;

  if p_subject_id is not null and not exists (
    select 1 from public.subjects s where s.id = p_subject_id and s.teacher_id = v_teacher_id
  ) then
    raise exception 'Course not found or access denied';
  end if;

  if p_classroom_id is not null and not exists (
    select 1
    from public.classrooms c
    join public.subjects s on s.id = c.subject_id
    where c.id = p_classroom_id and s.teacher_id = v_teacher_id
      and (p_subject_id is null or s.id = p_subject_id)
  ) then
    raise exception 'Classroom not found or access denied';
  end if;

  if v_status is not null and v_status not in ('active', 'inactive', 'needs_help', 'no_activity', 'excellent') then
    raise exception 'Invalid student status';
  end if;
  if v_order not in ('attention', 'accuracy', 'xp', 'last_activity', 'name') then
    v_order := 'attention';
  end if;

  with teacher_subjects as (
    select s.id, s.name
    from public.subjects s
    where s.teacher_id = v_teacher_id
      and coalesce(s.active, true)
      and not coalesce(s.is_archived, false)
  ),
  scoped_enrollments as (
    select e.id, e.student_id, e.subject_id, e.classroom_id, e.joined_at, s.name as subject_name, c.name as classroom_name
    from public.enrollments e
    join teacher_subjects s on s.id = e.subject_id
    left join public.classrooms c on c.id = e.classroom_id
    where (p_subject_id is null or e.subject_id = p_subject_id)
      and (p_classroom_id is null or e.classroom_id = p_classroom_id)
  ),
  student_context as (
    select
      e.student_id,
      min(e.joined_at) as imported_at,
      array_agg(distinct e.subject_id order by e.subject_id) as subject_ids,
      array_agg(distinct e.subject_name order by e.subject_name) as subject_names,
      array_agg(distinct e.classroom_id order by e.classroom_id) filter (where e.classroom_id is not null) as classroom_ids,
      array_agg(distinct coalesce(e.classroom_name, 'Clase principal') order by coalesce(e.classroom_name, 'Clase principal')) as classroom_names,
      jsonb_agg(jsonb_build_object(
        'subjectId', e.subject_id,
        'subjectName', e.subject_name,
        'classroomId', e.classroom_id,
        'classroomName', coalesce(e.classroom_name, 'Clase principal'),
        'joinedAt', e.joined_at
      ) order by e.joined_at, e.id) as course_contexts
    from scoped_enrollments e
    group by e.student_id
  ),
  scoped_questions as (
    select distinct q.id, q.subject_id, q.classroom_id, q.topic_id
    from public.questions q
    join teacher_subjects s on s.id = q.subject_id
    where coalesce(q.active, true)
      and (p_subject_id is null or q.subject_id = p_subject_id)
      and (p_classroom_id is null or q.classroom_id = p_classroom_id)
  ),
  available_question_counts as (
    select sc.student_id, count(distinct q.id)::int as available_questions
    from student_context sc
    join scoped_enrollments e on e.student_id = sc.student_id
    join scoped_questions q on q.subject_id = e.subject_id
      and (e.classroom_id is null or q.classroom_id is null or q.classroom_id = e.classroom_id)
    group by sc.student_id
  ),
  attempt_agg as (
    select
      sc.student_id,
      count(ah.id) filter (where q.id is not null)::int as attempts_count,
      count(ah.id) filter (where q.id is not null and ah.is_correct)::int as correct_count,
      count(distinct ah.question_id) filter (where q.id is not null)::int as answered_questions,
      coalesce(sum(coalesce(ah.earned_points, 0)) filter (where q.id is not null), 0)::int as earned_points,
      max(ah.attempted_at) filter (where q.id is not null) as last_activity_at
    from student_context sc
    left join public.attempt_history ah on ah.student_id = sc.student_id
    left join scoped_questions q on q.id = ah.question_id
    group by sc.student_id
  ),
  score_agg as (
    select
      sc.student_id,
      coalesce(sum(coalesce(ss.max_score, 0)), 0)::int as subject_xp,
      max(ss.played_at) as score_activity_at
    from student_context sc
    left join public.subject_scores ss on ss.student_id = sc.student_id
      and ss.subject_id = any(sc.subject_ids)
      and (p_classroom_id is null or ss.classroom_id = p_classroom_id)
    group by sc.student_id
  ),
  calculated as (
    select
      sc.student_id,
      coalesce(p.alias, 'Alumno sin perfil') as alias,
      p.email,
      coalesce(p.points, 0)::int as global_points,
      coalesce(sa.subject_xp, 0)::int as subject_xp,
      coalesce(aa.attempts_count, 0)::int as attempts_count,
      coalesce(aa.correct_count, 0)::int as correct_count,
      coalesce(aa.answered_questions, 0)::int as answered_questions,
      coalesce(aqc.available_questions, 0)::int as available_questions,
      case when coalesce(aa.attempts_count, 0) > 0 then round(100.0 * coalesce(aa.correct_count, 0) / aa.attempts_count)::int else 0 end as accuracy_percent,
      case when coalesce(aqc.available_questions, 0) > 0 then least(100, round(100.0 * coalesce(aa.answered_questions, 0) / aqc.available_questions)::int) else 0 end as participation_percent,
      greatest(aa.last_activity_at, sa.score_activity_at) as last_activity_at,
      sc.imported_at,
      sc.subject_ids,
      sc.subject_names,
      coalesce(sc.classroom_ids, '{}'::bigint[]) as classroom_ids,
      sc.classroom_names,
      sc.course_contexts,
      case
        when coalesce(aa.attempts_count, 0) = 0 and coalesce(sa.subject_xp, 0) = 0 then 'no_activity'
        when coalesce(aa.attempts_count, 0) >= 3 and (100.0 * coalesce(aa.correct_count, 0) / nullif(aa.attempts_count, 0)) < 50 then 'needs_help'
        when greatest(aa.last_activity_at, sa.score_activity_at) < now() - interval '14 days' then 'inactive'
        when coalesce(aa.attempts_count, 0) >= 5 and (100.0 * coalesce(aa.correct_count, 0) / nullif(aa.attempts_count, 0)) >= 85 then 'excellent'
        else 'active'
      end as status
    from student_context sc
    join public.profiles p on p.id = sc.student_id
      and p.role_id = 'student'
      and coalesce(p.active, true)
    left join attempt_agg aa on aa.student_id = sc.student_id
    left join score_agg sa on sa.student_id = sc.student_id
    left join available_question_counts aqc on aqc.student_id = sc.student_id
  ),
  filtered as (
    select *
    from calculated c
    where (v_status is null or c.status = v_status)
      and (
        v_search is null
        or c.alias ilike '%' || v_search || '%'
        or coalesce(c.email, '') ilike '%' || v_search || '%'
        or array_to_string(c.subject_names, ' ') ilike '%' || v_search || '%'
        or array_to_string(c.classroom_names, ' ') ilike '%' || v_search || '%'
      )
  ),
  page_rows as (
    select *
    from filtered
    order by
      case when v_order = 'attention' then case status when 'needs_help' then 1 when 'inactive' then 2 when 'no_activity' then 3 when 'active' then 4 else 5 end end,
      case when v_order = 'accuracy' then accuracy_percent end desc,
      case when v_order = 'xp' then subject_xp end desc,
      case when v_order = 'last_activity' then last_activity_at end desc nulls last,
      case when v_order = 'name' then alias end asc,
      alias asc,
      student_id
    limit v_limit offset v_offset
  ),
  item_rows as (
    select
      p.*,
      coalesce((
        select jsonb_agg(jsonb_build_object(
          'title', w.topic_title,
          'detail', w.subject_name,
          'mistakes', w.mistakes,
          'accuracyPercent', w.accuracy_percent
        ) order by w.mistakes desc, w.accuracy_percent asc)
        from (
          select
            coalesce(t.title, 'Práctica general') as topic_title,
            s.name as subject_name,
            count(ah.id) filter (where not ah.is_correct)::int as mistakes,
            case when count(ah.id) > 0 then round(100.0 * count(ah.id) filter (where ah.is_correct) / count(ah.id))::int else 0 end as accuracy_percent
          from public.attempt_history ah
          join scoped_questions q on q.id = ah.question_id
          join public.subjects s on s.id = q.subject_id
          left join public.subject_topics t on t.id = q.topic_id
          where ah.student_id = p.student_id
          group by t.id, t.title, s.id, s.name
          having count(ah.id) filter (where not ah.is_correct) > 0
          order by mistakes desc, accuracy_percent asc
          limit 4
        ) w
      ), '[]'::jsonb) as weak_areas,
      coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', r.id,
          'questionText', r.question_text,
          'topicTitle', r.topic_title,
          'subjectName', r.subject_name,
          'isCorrect', r.is_correct,
          'attemptedAt', r.attempted_at,
          'earnedPoints', r.earned_points
        ) order by r.attempted_at desc, r.id desc)
        from (
          select ah.id, q.text as question_text, coalesce(t.title, 'Práctica general') as topic_title,
            s.name as subject_name, ah.is_correct, ah.attempted_at, coalesce(ah.earned_points, 0)::int as earned_points
          from public.attempt_history ah
          join public.questions q on q.id = ah.question_id
          join public.subjects s on s.id = q.subject_id and s.teacher_id = v_teacher_id
          left join public.subject_topics t on t.id = q.topic_id
          where ah.student_id = p.student_id
            and (p_subject_id is null or q.subject_id = p_subject_id)
            and (p_classroom_id is null or q.classroom_id = p_classroom_id)
          order by ah.attempted_at desc, ah.id desc
          limit 8
        ) r
      ), '[]'::jsonb) as recent_attempts
    from page_rows p
  )
  select jsonb_build_object(
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', i.student_id,
        'alias', i.alias,
        'handle', '@' || regexp_replace(lower(i.alias), '\\s+', '', 'g'),
        'globalPoints', i.global_points,
        'subjectScore', i.subject_xp,
        'averageScore', round(i.accuracy_percent / 10.0, 1),
        'accuracyPercent', i.accuracy_percent,
        'challenges', i.attempts_count,
        'questions', i.answered_questions,
        'participation', i.participation_percent,
        'progress', i.participation_percent,
        'status', i.status,
        'hasActivity', i.attempts_count > 0 or i.subject_xp > 0,
        'subjectIds', to_jsonb(i.subject_ids),
        'subjectNames', to_jsonb(i.subject_names),
        'classroomIds', to_jsonb(i.classroom_ids),
        'classroomNames', to_jsonb(i.classroom_names),
        'courseContexts', i.course_contexts,
        'weakAreas', i.weak_areas,
        'recentAttempts', i.recent_attempts,
        'lastActivityAt', i.last_activity_at,
        'importedAt', i.imported_at
      ) order by
        case when v_order = 'attention' then case i.status when 'needs_help' then 1 when 'inactive' then 2 when 'no_activity' then 3 when 'active' then 4 else 5 end end,
        case when v_order = 'accuracy' then i.accuracy_percent end desc,
        case when v_order = 'xp' then i.subject_xp end desc,
        case when v_order = 'last_activity' then i.last_activity_at end desc nulls last,
        case when v_order = 'name' then i.alias end asc,
        i.alias asc
      ) from item_rows i
    ), '[]'::jsonb),
    'total', (select count(*)::int from filtered),
    'limit', v_limit,
    'offset', v_offset,
    'summary', jsonb_build_object(
      'total', (select count(*)::int from filtered),
      'active', (select count(*)::int from filtered where status in ('active', 'excellent')),
      'noActivity', (select count(*)::int from filtered where status = 'no_activity'),
      'needsHelp', (select count(*)::int from filtered where status in ('needs_help', 'inactive')),
      'withActivity', (select count(*)::int from filtered where attempts_count > 0 or subject_xp > 0),
      'averageXp', coalesce((select round(avg(subject_xp))::int from filtered where attempts_count > 0 or subject_xp > 0), 0),
      'averageGrade', coalesce((select round(avg(accuracy_percent / 10.0), 1) from filtered where attempts_count > 0), 0),
      'averageAccuracy', coalesce((select round(avg(accuracy_percent))::int from filtered where attempts_count > 0), 0),
      'completedChallenges', coalesce((select sum(attempts_count)::int from filtered), 0)
    ),
    'subjects', coalesce((
      select jsonb_agg(jsonb_build_object('id', s.id, 'name', s.name) order by s.name, s.id)
      from teacher_subjects s
    ), '[]'::jsonb),
    'classrooms', coalesce((
      select jsonb_agg(jsonb_build_object('id', c.id, 'subject_id', c.subject_id, 'name', c.name, 'academic_year', c.academic_year) order by c.name, c.id)
      from public.classrooms c
      join teacher_subjects s on s.id = c.subject_id
      where coalesce(c.active, true)
    ), '[]'::jsonb),
    'attention', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.priority, x.alias)
      from (
        select student_id as id, alias, status,
          case status when 'needs_help' then 1 when 'inactive' then 2 else 3 end as priority
        from filtered
        where status in ('needs_help', 'inactive')
        order by priority, alias
        limit 3
      ) x
    ), '[]'::jsonb),
    'pending', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.alias)
      from (
        select student_id as id, alias, status
        from filtered
        where status = 'no_activity'
        order by alias
        limit 3
      ) x
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.get_teacher_student_history_summary(
  p_student_id uuid,
  p_subject_id bigint default null,
  p_classroom_id bigint default null,
  p_period_days integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_days integer := least(greatest(coalesce(p_period_days, 30), 7), 365);
  v_result jsonb;
begin
  if v_teacher_id is null then raise exception 'Teacher session required'; end if;
  if not exists (
    select 1 from public.enrollments e
    join public.subjects s on s.id = e.subject_id
    where e.student_id = p_student_id and s.teacher_id = v_teacher_id
      and (p_subject_id is null or e.subject_id = p_subject_id)
      and (p_classroom_id is null or e.classroom_id = p_classroom_id)
  ) then
    raise exception 'Student not found or access denied';
  end if;

  with contexts as (
    select e.id, e.student_id, e.subject_id, e.classroom_id, e.joined_at,
      s.name as subject_name, s.academic_year as subject_year,
      c.name as classroom_name, c.code as classroom_code, c.academic_year as classroom_year
    from public.enrollments e
    join public.subjects s on s.id = e.subject_id and s.teacher_id = v_teacher_id
    left join public.classrooms c on c.id = e.classroom_id
    where e.student_id = p_student_id
      and (p_subject_id is null or e.subject_id = p_subject_id)
      and (p_classroom_id is null or e.classroom_id = p_classroom_id)
  ),
  scoped_questions as (
    select q.id, q.subject_id, q.classroom_id, q.topic_id, q.type, q.active
    from public.questions q
    where exists (
      select 1
      from contexts c
      where c.subject_id = q.subject_id
        and (c.classroom_id is null or q.classroom_id is null or q.classroom_id = c.classroom_id)
    )
  ),
  scoped_attempts as (
    select
      ah.id,
      ah.student_id,
      ah.question_id,
      ah.is_correct,
      ah.earned_points,
      ah.attempted_at,
      ah.manual_review_status,
      q.subject_id,
      q.classroom_id,
      q.topic_id,
      q.type as question_type
    from public.attempt_history ah
    join scoped_questions q on q.id = ah.question_id
    where ah.student_id = p_student_id
  ),
  current_period as (
    select * from scoped_attempts where attempted_at >= now() - make_interval(days => v_days)
  ),
  previous_period as (
    select * from scoped_attempts
    where attempted_at >= now() - make_interval(days => v_days * 2)
      and attempted_at < now() - make_interval(days => v_days)
  ),
  weak_topic as (
    select q.topic_id, coalesce(t.title, 'Práctica general') as topic_title,
      count(a.id)::int as attempts, count(a.id) filter (where not a.is_correct)::int as mistakes,
      case when count(a.id) > 0 then round(100.0 * count(a.id) filter (where a.is_correct) / count(a.id))::int else 0 end as accuracy
    from current_period a
    join scoped_questions q on q.id = a.question_id
    left join public.subject_topics t on t.id = q.topic_id
    group by q.topic_id, t.title
    having count(a.id) filter (where not a.is_correct) > 0
    order by mistakes desc, accuracy asc
    limit 1
  ),
  metrics as (
    select
      (select count(*)::int from current_period) as current_attempts,
      (select count(*)::int from current_period where is_correct) as current_correct,
      (select coalesce(sum(coalesce(earned_points, 0)), 0)::int from current_period) as current_xp,
      (select count(*)::int from previous_period) as previous_attempts,
      (select count(*)::int from previous_period where is_correct) as previous_correct,
      (select coalesce(sum(coalesce(earned_points, 0)), 0)::int from previous_period) as previous_xp,
      (select max(attempted_at) from scoped_attempts) as last_activity,
      (select count(*)::int from scoped_attempts where manual_review_status in ('pending', 'in_review', 'needs_changes')) as pending_reviews,
      (select count(distinct question_id)::int from current_period) as answered_questions,
      (select count(*)::int from scoped_questions where coalesce(active, true)) as available_questions
  )
  select jsonb_build_object(
    'profile', jsonb_build_object(
      'id', p.id,
      'alias', p.alias,
      'avatar', p.avatar,
      'points', p.points,
      'active', p.active,
      'createdAt', p.created_at
    ),
    'subjectsCount', (
      select count(*)::int from public.subjects s where s.teacher_id = v_teacher_id and coalesce(s.active, true) and not coalesce(s.is_archived, false)
    ),
    'courseContexts', coalesce((
      select jsonb_agg(jsonb_build_object(
        'enrollmentId', c.id,
        'subjectId', c.subject_id,
        'subjectName', c.subject_name,
        'classroomId', c.classroom_id,
        'classroomName', coalesce(c.classroom_name, 'Clase principal'),
        'classroomCode', c.classroom_code,
        'academicYear', coalesce(c.classroom_year, c.subject_year),
        'joinedAt', c.joined_at
      ) order by c.joined_at, c.id)
      from contexts c
    ), '[]'::jsonb),
    'summary', jsonb_build_object(
      'periodDays', v_days,
      'attempts', m.current_attempts,
      'correct', m.current_correct,
      'accuracyPercent', case when m.current_attempts > 0 then round(100.0 * m.current_correct / m.current_attempts)::int else null end,
      'earnedXp', m.current_xp,
      'lastActivityAt', m.last_activity,
      'pendingReviews', m.pending_reviews,
      'answeredQuestions', m.answered_questions,
      'availableQuestions', m.available_questions,
      'coveragePercent', case when m.available_questions > 0 then round(100.0 * m.answered_questions / m.available_questions)::int else null end
    ),
    'comparison', jsonb_build_object(
      'current', jsonb_build_object(
        'attempts', m.current_attempts,
        'accuracyPercent', case when m.current_attempts > 0 then round(100.0 * m.current_correct / m.current_attempts)::int else null end,
        'earnedXp', m.current_xp
      ),
      'previous', jsonb_build_object(
        'attempts', m.previous_attempts,
        'accuracyPercent', case when m.previous_attempts > 0 then round(100.0 * m.previous_correct / m.previous_attempts)::int else null end,
        'earnedXp', m.previous_xp
      ),
      'delta', jsonb_build_object(
        'attempts', m.current_attempts - m.previous_attempts,
        'accuracyPoints', coalesce(case when m.current_attempts > 0 then round(100.0 * m.current_correct / m.current_attempts)::int end, 0)
          - coalesce(case when m.previous_attempts > 0 then round(100.0 * m.previous_correct / m.previous_attempts)::int end, 0),
        'earnedXp', m.current_xp - m.previous_xp
      )
    ),
    'recommendation', case
      when m.current_attempts = 0 and m.last_activity is null then jsonb_build_object(
        'code', 'start', 'title', 'Ayudarle a empezar',
        'reason', 'No se ha registrado ninguna respuesta en los cursos seleccionados.',
        'actionLabel', 'Enviar recordatorio', 'topicId', null
      )
      when m.pending_reviews > 0 then jsonb_build_object(
        'code', 'review', 'title', 'Revisar respuestas pendientes',
        'reason', format('Hay %s respuesta(s) esperando una decisión docente.', m.pending_reviews),
        'actionLabel', 'Abrir revisiones', 'topicId', null
      )
      when exists (select 1 from weak_topic) then jsonb_build_object(
        'code', 'practice', 'title', 'Reforzar ' || (select topic_title from weak_topic),
        'reason', format('La precisión del tema es %s%% y acumula %s error(es).', (select accuracy from weak_topic), (select mistakes from weak_topic)),
        'actionLabel', 'Preparar práctica', 'topicId', (select topic_id from weak_topic)
      )
      when m.last_activity < now() - interval '14 days' then jsonb_build_object(
        'code', 'reengage', 'title', 'Recuperar la constancia',
        'reason', 'La última actividad supera los 14 días.',
        'actionLabel', 'Enviar recordatorio', 'topicId', null
      )
      else jsonb_build_object(
        'code', 'challenge', 'title', 'Proponer un nuevo reto',
        'reason', 'Mantiene una actividad estable y puede avanzar a contenido más exigente.',
        'actionLabel', 'Crear pregunta', 'topicId', null
      )
    end,
    'notes', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', n.id,
        'body', n.body,
        'subjectId', n.subject_id,
        'classroomId', n.classroom_id,
        'createdAt', n.created_at,
        'updatedAt', n.updated_at
      ) order by n.created_at desc, n.id desc)
      from (
        select n.id, n.body, n.subject_id, n.classroom_id, n.created_at, n.updated_at
        from public.teacher_student_notes n
        where n.teacher_id = v_teacher_id and n.student_id = p_student_id
          and (p_subject_id is null or n.subject_id is null or n.subject_id = p_subject_id)
          and (p_classroom_id is null or n.classroom_id is null or n.classroom_id = p_classroom_id)
        order by n.created_at desc, n.id desc
        limit 5
      ) n
    ), '[]'::jsonb)
  ) into v_result
  from public.profiles p
  cross join metrics m
  where p.id = p_student_id;

  return v_result;
end;
$$;

create or replace function public.get_teacher_student_history_timeline_page(
  p_student_id uuid,
  p_subject_id bigint default null,
  p_classroom_id bigint default null,
  p_limit integer default 20,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 100);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_result jsonb;
begin
  if v_teacher_id is null then raise exception 'Teacher session required'; end if;
  if not exists (
    select 1
    from public.enrollments e
    join public.subjects s on s.id = e.subject_id
    where e.student_id = p_student_id
      and s.teacher_id = v_teacher_id
      and (p_subject_id is null or e.subject_id = p_subject_id)
      and (p_classroom_id is null or e.classroom_id = p_classroom_id)
  ) then raise exception 'Student not found or access denied'; end if;

  with filtered as (
    select
      ah.id,
      ah.question_id,
      q.text as question_text,
      q.type as question_type,
      q.subject_id,
      s.name as subject_name,
      q.classroom_id,
      coalesce(c.name, 'Clase principal') as classroom_name,
      q.topic_id,
      coalesce(t.title, 'Práctica general') as topic_title,
      coalesce(ah.submitted_answer_text, a.text,
        case when ah.submitted_answer_payload is not null then 'Respuesta interactiva' else 'Sin respuesta registrada' end) as answer_text,
      ah.is_correct,
      coalesce(ah.earned_points, 0)::int as earned_points,
      ah.time_taken_seconds,
      coalesce(ah.hint_used, false) as hint_used,
      coalesce(ah.was_skipped, false) as was_skipped,
      ah.attempted_at,
      coalesce(ah.manual_review_status, 'not_required') as manual_review_status,
      ah.reviewed_at,
      ah.review_notes,
      q.difficulty,
      (select count(*)::int from public.manual_review_comments m where m.attempt_history_id = ah.id) as comments_count
    from public.attempt_history ah
    join public.questions q on q.id = ah.question_id
    join public.subjects s on s.id = q.subject_id and s.teacher_id = v_teacher_id
    left join public.classrooms c on c.id = q.classroom_id
    left join public.subject_topics t on t.id = q.topic_id
    left join public.answers a on a.id = ah.answer_id
    where ah.student_id = p_student_id
      and exists (
        select 1
        from public.enrollments e
        where e.student_id = p_student_id
          and e.subject_id = q.subject_id
          and (e.classroom_id is null or q.classroom_id is null or e.classroom_id = q.classroom_id)
      )
      and (p_subject_id is null or q.subject_id = p_subject_id)
      and (p_classroom_id is null or q.classroom_id is null or q.classroom_id = p_classroom_id)
  ),
  page_rows as (
    select * from filtered order by attempted_at desc, id desc limit v_limit offset v_offset
  )
  select jsonb_build_object(
    'items', coalesce((select jsonb_agg(to_jsonb(p) order by p.attempted_at desc, p.id desc) from page_rows p), '[]'::jsonb),
    'total', (select count(*)::int from filtered),
    'limit', v_limit,
    'offset', v_offset
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.get_teacher_student_history_weaknesses(
  p_student_id uuid,
  p_subject_id bigint default null,
  p_classroom_id bigint default null,
  p_period_days integer default 90
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_days integer := least(greatest(coalesce(p_period_days, 90), 7), 365);
  v_result jsonb;
begin
  if v_teacher_id is null then raise exception 'Teacher session required'; end if;
  if not exists (
    select 1
    from public.enrollments e
    join public.subjects s on s.id = e.subject_id
    where e.student_id = p_student_id
      and s.teacher_id = v_teacher_id
      and (p_subject_id is null or e.subject_id = p_subject_id)
      and (p_classroom_id is null or e.classroom_id = p_classroom_id)
  ) then raise exception 'Student not found or access denied'; end if;

  with rows as (
    select q.subject_id, s.name as subject_name, q.topic_id, coalesce(t.title, 'Práctica general') as topic_title,
      count(ah.id)::int as attempts,
      count(ah.id) filter (where not ah.is_correct)::int as mistakes,
      round(100.0 * count(ah.id) filter (where ah.is_correct) / nullif(count(ah.id), 0))::int as accuracy_percent,
      max(ah.attempted_at) as last_attempt_at
    from public.attempt_history ah
    join public.questions q on q.id = ah.question_id
    join public.subjects s on s.id = q.subject_id and s.teacher_id = v_teacher_id
    left join public.subject_topics t on t.id = q.topic_id
    where ah.student_id = p_student_id
      and exists (
        select 1
        from public.enrollments e
        where e.student_id = p_student_id
          and e.subject_id = q.subject_id
          and (e.classroom_id is null or q.classroom_id is null or e.classroom_id = q.classroom_id)
      )
      and ah.attempted_at >= now() - make_interval(days => v_days)
      and (p_subject_id is null or q.subject_id = p_subject_id)
      and (p_classroom_id is null or q.classroom_id is null or q.classroom_id = p_classroom_id)
    group by q.subject_id, s.name, q.topic_id, t.title
    having count(ah.id) filter (where not ah.is_correct) > 0
    order by mistakes desc, accuracy_percent asc, last_attempt_at desc
  )
  select jsonb_build_object(
    'items', coalesce((select jsonb_agg(to_jsonb(r) order by r.mistakes desc, r.accuracy_percent asc) from rows r), '[]'::jsonb),
    'periodDays', v_days
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.get_teacher_student_history_reviews_page(
  p_student_id uuid,
  p_subject_id bigint default null,
  p_classroom_id bigint default null,
  p_limit integer default 20,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 100);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_result jsonb;
begin
  if v_teacher_id is null then raise exception 'Teacher session required'; end if;
  if not exists (
    select 1
    from public.enrollments e
    join public.subjects s on s.id = e.subject_id
    where e.student_id = p_student_id
      and s.teacher_id = v_teacher_id
      and (p_subject_id is null or e.subject_id = p_subject_id)
      and (p_classroom_id is null or e.classroom_id = p_classroom_id)
  ) then raise exception 'Student not found or access denied'; end if;

  with filtered as (
    select ah.id, ah.question_id, q.text as question_text, s.name as subject_name,
      coalesce(t.title, 'Práctica general') as topic_title,
      ah.submitted_answer_text as answer_text,
      coalesce(ah.manual_review_status, 'not_required') as status,
      ah.reviewed_at, ah.review_notes, ah.attempted_at,
      (select count(*)::int from public.manual_review_comments m where m.attempt_history_id = ah.id) as comments_count
    from public.attempt_history ah
    join public.questions q on q.id = ah.question_id
    join public.subjects s on s.id = q.subject_id and s.teacher_id = v_teacher_id
    left join public.subject_topics t on t.id = q.topic_id
    where ah.student_id = p_student_id
      and exists (
        select 1
        from public.enrollments e
        where e.student_id = p_student_id
          and e.subject_id = q.subject_id
          and (e.classroom_id is null or q.classroom_id is null or e.classroom_id = q.classroom_id)
      )
      and q.type = 'open_answer'
      and coalesce(ah.manual_review_status, 'not_required') <> 'not_required'
      and (p_subject_id is null or q.subject_id = p_subject_id)
      and (p_classroom_id is null or q.classroom_id is null or q.classroom_id = p_classroom_id)
  ), page_rows as (
    select * from filtered
    order by case status when 'pending' then 1 when 'in_review' then 2 when 'needs_changes' then 3 else 4 end,
      attempted_at desc, id desc
    limit v_limit offset v_offset
  )
  select jsonb_build_object(
    'items', coalesce((select jsonb_agg(to_jsonb(p) order by p.attempted_at desc, p.id desc) from page_rows p), '[]'::jsonb),
    'total', (select count(*)::int from filtered),
    'limit', v_limit,
    'offset', v_offset
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.get_teacher_student_history_metrics(
  p_student_id uuid,
  p_subject_id bigint default null,
  p_classroom_id bigint default null,
  p_period_days integer default 90
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_days integer := least(greatest(coalesce(p_period_days, 90), 7), 365);
  v_result jsonb;
begin
  if v_teacher_id is null then raise exception 'Teacher session required'; end if;
  if not exists (
    select 1
    from public.enrollments e
    join public.subjects s on s.id = e.subject_id
    where e.student_id = p_student_id
      and s.teacher_id = v_teacher_id
      and (p_subject_id is null or e.subject_id = p_subject_id)
      and (p_classroom_id is null or e.classroom_id = p_classroom_id)
  ) then raise exception 'Student not found or access denied'; end if;

  with attempts as (
    select
      ah.attempted_at,
      ah.is_correct,
      coalesce(ah.earned_points, 0)::int as earned_points,
      q.subject_id,
      q.classroom_id,
      q.topic_id,
      s.name as subject_name,
      coalesce(t.title, 'Práctica general') as topic_title
    from public.attempt_history ah
    join public.questions q on q.id = ah.question_id
    join public.subjects s on s.id = q.subject_id and s.teacher_id = v_teacher_id
    left join public.subject_topics t on t.id = q.topic_id
    where ah.student_id = p_student_id
      and exists (
        select 1
        from public.enrollments e
        where e.student_id = p_student_id
          and e.subject_id = q.subject_id
          and (e.classroom_id is null or q.classroom_id is null or e.classroom_id = q.classroom_id)
      )
      and ah.attempted_at >= now() - make_interval(days => v_days)
      and (p_subject_id is null or q.subject_id = p_subject_id)
      and (p_classroom_id is null or q.classroom_id is null or q.classroom_id = p_classroom_id)
  ), daily as (
    select attempted_at::date as day, count(*)::int as attempts,
      count(*) filter (where is_correct)::int as correct,
      coalesce(sum(coalesce(earned_points, 0)), 0)::int as earned_xp
    from attempts group by attempted_at::date order by day
  ), topic_rows as (
    select subject_id, subject_name, topic_id, topic_title, count(*)::int as attempts,
      count(*) filter (where is_correct)::int as correct,
      round(100.0 * count(*) filter (where is_correct) / nullif(count(*), 0))::int as accuracy_percent,
      coalesce(sum(coalesce(earned_points, 0)), 0)::int as earned_xp,
      max(attempted_at) as last_activity_at
    from attempts group by subject_id, subject_name, topic_id, topic_title
  )
  select jsonb_build_object(
    'periodDays', v_days,
    'evolution', coalesce((
      select jsonb_agg(jsonb_build_object(
        'date', d.day,
        'attempts', d.attempts,
        'correct', d.correct,
        'accuracyPercent', case when d.attempts > 0 then round(100.0 * d.correct / d.attempts)::int else 0 end,
        'earnedXp', d.earned_xp
      ) order by d.day) from daily d
    ), '[]'::jsonb),
    'topics', coalesce((select jsonb_agg(to_jsonb(t) order by t.last_activity_at desc, t.topic_title) from topic_rows t), '[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.add_teacher_student_note(
  p_student_id uuid,
  p_body text,
  p_subject_id bigint default null,
  p_classroom_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher_id uuid := auth.uid();
  v_note public.teacher_student_notes%rowtype;
begin
  if v_teacher_id is null then raise exception 'Teacher session required'; end if;
  if nullif(trim(coalesce(p_body, '')), '') is null then raise exception 'Write a note'; end if;
  if not exists (
    select 1 from public.enrollments e join public.subjects s on s.id = e.subject_id
    where e.student_id = p_student_id and s.teacher_id = v_teacher_id
      and (p_subject_id is null or e.subject_id = p_subject_id)
      and (p_classroom_id is null or e.classroom_id = p_classroom_id)
  ) then raise exception 'Student not found or access denied'; end if;

  insert into public.teacher_student_notes(teacher_id, student_id, subject_id, classroom_id, body)
  values (v_teacher_id, p_student_id, p_subject_id, p_classroom_id, trim(p_body))
  returning * into v_note;

  insert into public.teacher_audit_logs(teacher_id, action, target_table, target_id, metadata)
  values (v_teacher_id, 'teacher.student.note.add', 'profiles', p_student_id::text,
    jsonb_build_object('note_id', v_note.id, 'subject_id', p_subject_id, 'classroom_id', p_classroom_id));

  return jsonb_build_object(
    'id', v_note.id,
    'body', v_note.body,
    'subjectId', v_note.subject_id,
    'classroomId', v_note.classroom_id,
    'createdAt', v_note.created_at,
    'updatedAt', v_note.updated_at
  );
end;
$$;

revoke all on function public.get_teacher_topic_summary(bigint) from public, anon;
revoke all on function public.get_teacher_topic_questions_page(bigint, integer, text, text, integer, integer) from public, anon;
revoke all on function public.archive_teacher_topic(bigint) from public, anon;
revoke all on function public.get_teacher_students_page(bigint, bigint, text, text, text, integer, integer) from public, anon;
revoke all on function public.get_teacher_student_history_summary(uuid, bigint, bigint, integer) from public, anon;
revoke all on function public.get_teacher_student_history_timeline_page(uuid, bigint, bigint, integer, integer) from public, anon;
revoke all on function public.get_teacher_student_history_weaknesses(uuid, bigint, bigint, integer) from public, anon;
revoke all on function public.get_teacher_student_history_reviews_page(uuid, bigint, bigint, integer, integer) from public, anon;
revoke all on function public.get_teacher_student_history_metrics(uuid, bigint, bigint, integer) from public, anon;
revoke all on function public.add_teacher_student_note(uuid, text, bigint, bigint) from public, anon;

grant execute on function public.get_teacher_topic_summary(bigint) to authenticated;
grant execute on function public.get_teacher_topic_questions_page(bigint, integer, text, text, integer, integer) to authenticated;
grant execute on function public.archive_teacher_topic(bigint) to authenticated;
grant execute on function public.get_teacher_students_page(bigint, bigint, text, text, text, integer, integer) to authenticated;
grant execute on function public.get_teacher_student_history_summary(uuid, bigint, bigint, integer) to authenticated;
grant execute on function public.get_teacher_student_history_timeline_page(uuid, bigint, bigint, integer, integer) to authenticated;
grant execute on function public.get_teacher_student_history_weaknesses(uuid, bigint, bigint, integer) to authenticated;
grant execute on function public.get_teacher_student_history_reviews_page(uuid, bigint, bigint, integer, integer) to authenticated;
grant execute on function public.get_teacher_student_history_metrics(uuid, bigint, bigint, integer) to authenticated;
grant execute on function public.add_teacher_student_note(uuid, text, bigint, bigint) to authenticated;

comment on function public.get_teacher_students_page(bigint, bigint, text, text, text, integer, integer) is
  'Returns server-calculated teacher student directory rows with accuracy, participation, last activity, status, answered questions and XP.';
comment on function public.get_teacher_topic_questions_page(bigint, integer, text, text, integer, integer) is
  'Returns a paginated teacher-owned topic question list without downloading complete answer banks.';
comment on table public.teacher_student_notes is
  'Private teacher notes attached to an enrolled student and optionally scoped to a course or classroom.';

notify pgrst, 'reload schema';
