create table if not exists public.teacher_audit_logs (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references public.profiles(id),
  action text not null,
  target_table text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists teacher_audit_logs_teacher_created_at_idx
  on public.teacher_audit_logs(teacher_id, created_at desc);

create index if not exists teacher_audit_logs_action_created_at_idx
  on public.teacher_audit_logs(action, created_at desc);

create index if not exists teacher_audit_logs_target_idx
  on public.teacher_audit_logs(target_table, target_id);

alter table public.teacher_audit_logs enable row level security;

drop policy if exists "teacher_select_own_teacher_audit_logs" on public.teacher_audit_logs;
create policy "teacher_select_own_teacher_audit_logs"
on public.teacher_audit_logs for select to authenticated
using (teacher_id = auth.uid() or public.is_admin());

grant select on public.teacher_audit_logs to authenticated;

comment on table public.teacher_audit_logs is 'Registro de acciones sensibles ejecutadas por profesores desde Edge Functions.';
comment on column public.teacher_audit_logs.action is 'Nombre estable de la acción ejecutada, por ejemplo teacher.question.delete.';
comment on column public.teacher_audit_logs.metadata is 'Datos no sensibles que ayudan a justificar y reconstruir la acción.';
