create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  target_table text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_admin_created_at_idx
  on public.admin_audit_log(admin_id, created_at desc);

create index if not exists admin_audit_log_action_created_at_idx
  on public.admin_audit_log(action, created_at desc);

alter table public.admin_audit_log enable row level security;

drop policy if exists "admin_select_admin_audit_log" on public.admin_audit_log;
create policy "admin_select_admin_audit_log"
on public.admin_audit_log for select to authenticated
using (public.is_admin());

grant select on public.admin_audit_log to authenticated;
