create extension if not exists pgcrypto;

create table if not exists public.roles (
  id text primary key,
  name text not null unique
);

insert into public.roles (id, name)
values
  ('student', 'Alumno'),
  ('teacher', 'Profesor')
on conflict (id) do nothing;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  alias text not null,
  avatar text,
  points integer default 0,
  role_id text references public.roles(id),
  active boolean default true,
  visibility text not null default 'private' check (visibility in ('public', 'private')),
  created_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  teacher_id uuid references public.profiles(id) on delete set null,
  name text not null,
  description text,
  icon text,
  code text not null unique,
  theme_color text,
  active boolean default true,
  is_archived boolean not null default false,
  education_level text,
  academic_year text,
  subject_label text,
  created_at timestamptz not null default now()
);

create table if not exists public.classrooms (
  id bigint generated by default as identity primary key,
  subject_id bigint references public.subjects(id) on delete cascade,
  name text not null,
  academic_year text,
  created_at timestamptz not null default now()
);

create table if not exists public.subject_topics (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  title text not null,
  description text,
  icon text,
  sort_order integer default 1,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  subject_id bigint references public.subjects(id) on delete cascade,
  topic_id bigint references public.subject_topics(id) on delete set null,
  type text not null,
  text text not null,
  points_base integer default 10,
  time_limit_seconds integer default 30,
  difficulty integer default 1,
  explanation text,
  active boolean default true,
  created_at timestamptz not null default now()
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  question_id bigint references public.questions(id) on delete cascade,
  text text not null,
  is_correct boolean default false,
  sort_order integer default 1
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (student_id, subject_id)
);

create table if not exists public.subject_scores (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  max_score integer default 0,
  correct_answers integer default 0,
  played_days date[] default '{}'::date[],
  played_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, subject_id)
);

create table if not exists public.topic_scores (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  topic_id bigint not null references public.subject_topics(id) on delete cascade,
  max_score integer default 0,
  played_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, topic_id)
);

create table if not exists public.attempt_history (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  answer_id bigint references public.answers(id) on delete set null,
  is_correct boolean not null,
  time_taken_seconds integer,
  attempted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.student_badges (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  badge_id text not null,
  reward_xp integer default 0,
  awarded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (student_id, badge_id)
);

create table if not exists public.user_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  language text default 'es-ES',
  timezone text default 'Europe/Madrid',
  date_format text default 'DD/MM/YYYY',
  time_format text default '24h',
  week_start text default 'monday',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_notification_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  push_enabled boolean not null default false,
  email_enabled boolean not null default false,
  daily_summary_enabled boolean not null default false,
  activity_enabled boolean not null default true,
  news_enabled boolean not null default false,
  frequency text not null default 'daily',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_state (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  notification_id text not null,
  is_read boolean not null default false,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, notification_id)
);

create table if not exists public.user_support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'student',
  category text not null,
  subject text not null,
  message text not null,
  contact_email text,
  priority text not null default 'medium',
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists visibility text not null default 'private';
alter table public.subjects add column if not exists is_archived boolean not null default false;
alter table public.subjects add column if not exists education_level text;
alter table public.subjects add column if not exists academic_year text;
alter table public.subjects add column if not exists subject_label text;
alter table public.questions add column if not exists topic_id bigint references public.subject_topics(id) on delete set null;
alter table public.questions add column if not exists explanation text;
alter table public.subject_scores add column if not exists correct_answers integer default 0;
alter table public.subject_scores add column if not exists played_days date[] default '{}'::date[];
alter table public.subject_scores add column if not exists played_at timestamptz;

create index if not exists subjects_teacher_id_idx on public.subjects(teacher_id);
create index if not exists subjects_code_idx on public.subjects(code);
create index if not exists subject_topics_subject_id_idx on public.subject_topics(subject_id);
create index if not exists questions_subject_id_idx on public.questions(subject_id);
create index if not exists questions_topic_id_idx on public.questions(topic_id);
create index if not exists answers_question_id_idx on public.answers(question_id);
create index if not exists enrollments_subject_id_idx on public.enrollments(subject_id);
create index if not exists enrollments_student_id_idx on public.enrollments(student_id);
create index if not exists subject_scores_subject_id_idx on public.subject_scores(subject_id);
create index if not exists subject_scores_student_id_idx on public.subject_scores(student_id);
create index if not exists topic_scores_topic_id_idx on public.topic_scores(topic_id);
create index if not exists attempt_history_student_id_idx on public.attempt_history(student_id);
create index if not exists attempt_history_question_id_idx on public.attempt_history(question_id);
create index if not exists student_badges_student_id_idx on public.student_badges(student_id);
create index if not exists user_support_tickets_user_id_idx on public.user_support_tickets(user_id);
