export { AdminHomeScreen, AdminDashboard } from './portal/AdminDashboard'
export { AdminTeachersScreen, AdminTeachersSection } from './portal/AdminTeachersSection'
export { AdminStudentsScreen, AdminStudentsSection } from './portal/AdminStudentsSection'
export { AdminCoursesScreen, AdminCoursesSection } from './portal/AdminCoursesSection'
export { AdminClassroomsScreen, AdminClassroomsSection } from './portal/AdminClassroomsSection'
export { AdminSupportScreen, AdminSupportSection } from './portal/AdminSupportSection'
export { AdminAuditScreen, AdminAuditSection } from './portal/AdminAuditSection'
