import React from 'react'
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { AppButton } from '../../ui'
import { useAppTheme } from '../../../lib/appTheme'
import { useResponsiveLayout } from '../../../lib/responsive'
import { formatAdminPushDate, formatAdminPushRelative, getAdminPushErrorLabel, getAdminPushPlatformLabel, getAdminPushPriorityLabel, getAdminPushRoleLabel, getAdminPushStatusLabel, getAdminPushTypeLabel } from '../../../lib/adminPushPresentation'
import type { AdminPushDeliveryDetail } from '../types/admin'

export default function AdminPushDeliveryDetailDrawer({ acting, canManage, detail, loading, onCancel, onClose, onProcessNow, onRetry, visible }: { acting: boolean; canManage: boolean; detail: AdminPushDeliveryDetail | null; loading: boolean; onCancel: () => void; onClose: () => void; onProcessNow: () => void; onRetry: () => void; visible: boolean }) {
  const { tokens } = useAppTheme()
  const responsive = useResponsiveLayout()
  const issue = detail ? getAdminPushErrorLabel(detail.queue.last_error_code, detail.queue.skip_reason) : null
  const status = detail?.queue.status

  return (
    <Modal transparent visible={visible} animationType={responsive.isDesktop ? 'fade' : 'slide'} onRequestClose={onClose}>
      <View style={[styles.overlay, { backgroundColor: tokens.background.overlay, justifyContent: responsive.isDesktop ? 'flex-end' : 'flex-end', flexDirection: responsive.isDesktop ? 'row' : 'column' }]}>
        <Pressable accessibilityLabel="Cerrar detalle del envío" onPress={onClose} style={StyleSheet.absoluteFill} />
        <View style={[styles.sheet, responsive.isDesktop ? styles.desktopSheet : styles.mobileSheet, { backgroundColor: tokens.surface.default, borderColor: tokens.border.default }]}>
          <View style={[styles.header, { borderBottomColor: tokens.border.subtle }]}>
            <View className="min-w-0 flex-1"><Text accessibilityRole="header" className="text-[21px] font-black text-text-primary">Detalle de entrega push</Text><Text className="mt-1 text-[12px] text-text-muted">Notificación persistente y entregas por dispositivo.</Text></View>
            <AppButton accessibilityLabel="Cerrar detalle" icon="close" iconOnly size="sm" variant="ghost" onPress={onClose} />
          </View>
          {loading ? <View className="flex-1 items-center justify-center"><ActivityIndicator color={tokens.brand.admin} /><Text className="mt-3 text-[13px] text-text-muted">Cargando detalle...</Text></View> : detail ? (
            <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
              <DetailSection title="Notificación" icon="notifications-outline"><DetailRow label="Título" value={detail.notification.title} /><DetailRow label="Mensaje" value={detail.notification.description} /><DetailRow label="Tipo" value={getAdminPushTypeLabel(detail.notification.type)} /><DetailRow label="Creada" value={formatAdminPushDate(detail.notification.created_at)} /></DetailSection>
              <DetailSection title="Destinatario" icon="person-outline"><DetailRow label="Usuario" value={detail.recipient.alias} /><DetailRow label="Rol" value={getAdminPushRoleLabel(detail.recipient.role)} /><DetailRow label="Estado" value={detail.recipient.active ? 'Activo' : 'Inactivo'} /></DetailSection>
              <DetailSection title="Estado y cola" icon="git-compare-outline"><DetailRow label="Estado" value={getAdminPushStatusLabel(detail.queue.status)} /><DetailRow label="Prioridad" value={getAdminPushPriorityLabel(detail.queue.priority)} /><DetailRow label="Intentos" value={`${detail.queue.attempts} de ${detail.queue.max_attempts}`} /><DetailRow label="Próximo intento" value={status === 'pending' ? formatAdminPushDate(detail.queue.next_attempt_at) : '—'} /><DetailRow label="Actualización" value={formatAdminPushDate(detail.queue.updated_at)} /></DetailSection>
              {Object.keys(detail.context || {}).length > 0 ? <DetailSection title="Contexto" icon="link-outline"><DetailRow label="Curso" value={detail.context.subject_name || '—'} /><DetailRow label="Clase" value={detail.context.classroom_name || '—'} /><DetailRow label="Ámbito" value={detail.context.classroom_name ? 'Clase del curso' : detail.context.subject_name ? 'Curso' : 'Información de la notificación'} /></DetailSection> : null}
              {issue ? <View className="rounded-2xl border border-semantic-warning bg-semantic-surface-warning p-4"><Text className="font-black text-text-primary">{issue}</Text></View> : null}
              <DetailSection title={`Dispositivos registrados · ${detail.devices.length}`} icon="phone-portrait-outline">{detail.devices.length ? detail.devices.map((device) => <View key={device.id} className="mb-2 rounded-xl border border-border-default bg-surface-raised p-3"><View className="flex-row items-center justify-between gap-3"><Text className="min-w-0 flex-1 font-black text-text-primary" numberOfLines={2}>{device.device_name || getAdminPushPlatformLabel(device.platform)}</Text><Text className={`text-[11px] font-black ${device.active ? 'text-semantic-success' : 'text-text-muted'}`}>{device.active ? 'Activo' : 'Inactivo'}</Text></View><Text className="mt-1 text-[12px] text-text-secondary">{getAdminPushPlatformLabel(device.platform)}{device.app_version ? ` · OmniQuest ${device.app_version}` : ''}</Text><Text className="mt-1 text-[11px] text-text-muted">Última actividad: {formatAdminPushRelative(device.last_seen_at)}</Text></View>) : <Text className="text-[12px] text-text-muted">No hay dispositivos registrados para esta cuenta.</Text>}</DetailSection>
              <DetailSection title={`Entregas del ciclo actual · ${detail.deliveries.length}`} icon="paper-plane-outline">{detail.deliveries.length ? detail.deliveries.map((delivery) => { const deliveryIssue = getAdminPushErrorLabel(delivery.error_code); return <View key={delivery.id} className="mb-2 rounded-xl border border-border-default bg-surface-raised p-3"><View className="flex-row items-start justify-between gap-3"><View className="min-w-0 flex-1"><Text className="font-black text-text-primary">{delivery.device?.device_name || (delivery.device ? getAdminPushPlatformLabel(delivery.device.platform) : 'Dispositivo no disponible')}</Text><Text className="mt-1 text-[12px] text-text-secondary">{getAdminPushStatusLabel(delivery.status === 'ticketed' ? 'waiting_receipt' : delivery.status === 'delivered' ? 'completed' : delivery.status)}</Text></View><Text className="text-[11px] font-black text-text-muted">Intento {delivery.attempt_number}</Text></View>{deliveryIssue ? <Text className="mt-2 text-[12px] font-bold text-semantic-warning">{deliveryIssue}</Text> : null}<Text className="mt-2 text-[11px] text-text-muted">Enviado: {formatAdminPushDate(delivery.sent_at)} · Confirmado: {formatAdminPushDate(delivery.delivered_at || delivery.receipt_checked_at)}</Text></View> }) : <Text className="text-[12px] text-text-muted">Todavía no se ha generado una entrega por dispositivo.</Text>}</DetailSection>
            </ScrollView>
          ) : <View className="flex-1 items-center justify-center px-6"><Text className="text-center text-[13px] text-text-muted">No se pudo cargar este envío.</Text></View>}
          {detail && canManage ? <View style={[styles.footer, { borderTopColor: tokens.border.subtle }]}>{status === 'pending' ? <><AppButton label="Procesar ahora" icon="flash-outline" loading={acting} onPress={onProcessNow} /><AppButton label="Cancelar envío" icon="close-circle-outline" variant="danger" disabled={acting} onPress={onCancel} /></> : status === 'failed' ? <AppButton label="Reintentar" icon="refresh-outline" loading={acting} onPress={onRetry} /> : <Text className="text-[12px] text-text-muted">Este estado es solo de consulta.</Text>}</View> : null}
        </View>
      </View>
    </Modal>
  )
}

function DetailSection({ children, icon, title }: { children: React.ReactNode; icon: keyof typeof Ionicons.glyphMap; title: string }) { const { tokens } = useAppTheme(); return <View className="rounded-2xl border border-border-default bg-surface-default p-4"><View className="mb-3 flex-row items-center gap-2"><Ionicons name={icon} size={17} color={tokens.brand.admin} /><Text accessibilityRole="header" className="font-black text-text-primary">{title}</Text></View>{children}</View> }
function DetailRow({ label, value }: { label: string; value: string }) { return <View className="mb-2 flex-row items-start gap-3"><Text className="w-[108px] shrink-0 text-[11px] font-bold text-text-muted">{label}</Text><Text className="min-w-0 flex-1 text-[12px] leading-5 text-text-secondary">{value}</Text></View> }

const styles = StyleSheet.create({ overlay: { flex: 1 }, sheet: { borderWidth: 1, overflow: 'hidden' }, desktopSheet: { width: 570, height: '100%', borderTopLeftRadius: 26, borderBottomLeftRadius: 26 }, mobileSheet: { width: '100%', maxHeight: '92%', borderTopLeftRadius: 28, borderTopRightRadius: 28 }, header: { paddingHorizontal: 20, paddingVertical: 17, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'flex-start', gap: 12 }, content: { padding: 18, gap: 12, paddingBottom: 28 }, footer: { borderTopWidth: 1, paddingHorizontal: 18, paddingVertical: 14, flexDirection: 'row', flexWrap: 'wrap', gap: 10 } })
