import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (path) => readFileSync(join(root, path), 'utf8')

test('course create/edit uses free-text academic fields and the exact displayed invite code', () => {
  const form = read('components/teacher/TeacherSubjectForm.tsx')
  assert.doesNotMatch(form, /import AppDropdown/)
  assert.match(form, /<TextFieldCard icon="people-outline"[\s\S]*label="Nivel educativo"/)
  assert.match(form, /<TextFieldCard icon="calendar-outline"[\s\S]*label="Año académico \(opcional\)"/)
  assert.match(form, /<TextInput[\s\S]*accessibilityLabel=\{label\}[\s\S]*onChangeText=\{onChange\}/)
  assert.doesNotMatch(form, /label="Materia \(opcional\)"/)
  assert.doesNotMatch(form, /subjectLabel|p_subject_label/)
  assert.match(form, /const startYear = now\.getMonth\(\) >= 8 \? calendarYear : calendarYear - 1/)
  assert.match(form, /p_code: code/)
  assert.match(form, /El código mostrado será exactamente el que se guardará al crear el curso\./)
  assert.doesNotMatch(form, /index \+ 1/)
})

test('course edit preview uses real enrolments and transactional mobile actions protect unsaved changes', () => {
  const form = read('components/teacher/TeacherSubjectForm.tsx')
  assert.match(form, /from\('enrollments'\)\.select\('student_id'\)\.eq\('subject_id'/)
  assert.match(form, /new Set\(enrollmentRows\.map\(\(row\) => row\.student_id\)\)\.size/)
  assert.match(form, /Descartar cambios/)
  assert.match(form, /Hay cambios sin guardar\. Si sales ahora se perderán\./)
  assert.match(form, /addListener\?\.\('beforeRemove'/)
  assert.match(form, /beforeunload/)
  assert.match(form, /absolute bottom-0 left-0 right-0/)
  assert.doesNotMatch(form, /TeacherBottomNav/)
  assert.match(form, /showGlobalSearch=\{false\}/)
  assert.match(form, /title=\{isEdit \? 'Editar curso' : 'Nuevo curso'\}/)
  assert.match(form, /'Crear curso'/)
  assert.doesNotMatch(form, /'Crear Curso'/)
})

test('transactional course and question forms hide the global search', () => {
  const header = read('components/teacher/TeacherPageHeader.tsx')
  const courseForm = read('components/teacher/TeacherSubjectForm.tsx')
  const questionForm = read('components/teacher/TeacherQuestionForm.tsx')
  assert.match(header, /showGlobalSearch\?: boolean/)
  assert.match(header, /showGlobalSearch = true/)
  assert.match(courseForm, /showGlobalSearch=\{false\}/)
  assert.match(questionForm, /showGlobalSearch=\{false\}/)
})

test('course detail keeps a persistent class context across all tabs and URLs', () => {
  const screen = read('app/(teacher)/subject/[id].tsx')
  const structure = read('components/teacher/subject/SubjectCourseStructure.tsx')
  const hook = read('features/teacher-subject/useTeacherSubjectDetail.ts')
  const selectorIndex = screen.indexOf('<SubjectClassroomContextSelector')
  const tabsIndex = screen.indexOf('<AppTabs<SubjectTabKey>')
  assert.ok(selectorIndex >= 0 && tabsIndex > selectorIndex)
  assert.match(structure, /export function SubjectClassroomContextSelector/)
  assert.match(structure, /Este contexto se mantiene al cambiar entre Resumen, Temas, Preguntas, Alumnos y Analítica\./)
  assert.match(hook, /router\.setParams\(\{ classroomId: String\(nextClassroomId\) \}/)
  assert.match(screen, /classroomId=\$\{classroomId\}/)
})

test('course analytics uses one metric definition, evaluated-only grade bands and real weekly activity', () => {
  const migration = read('supabase/migrations/20260810104500_teacher_course_detail_mobile_hardening.sql')
  const students = read('components/teacher/subject/SubjectStudentsTab.tsx')
  const analytics = read('components/teacher/subject/SubjectAnalyticsTab.tsx')
  const summary = read('components/teacher/subject/SubjectSummaryTab.tsx')
  assert.match(migration, /'activeThisWeek'.*interval '7 days'/s)
  assert.match(migration, /100\.0 \* sum\(correct_answers\) \/ sum\(total_answers\)/)
  assert.match(migration, /from rows where has_activity and grade >= 9/)
  assert.match(migration, /Notable \(7-8,9\)/)
  assert.match(migration, /Aprobado \(5-6,9\)/)
  assert.match(migration, /Suspenso \(<5\)/)
  assert.doesNotMatch(migration, /Bueno \(/)
  assert.doesNotMatch(migration, /Regular \(/)
  assert.match(students, /GradeDistributionBars distribution=\{gradeDistribution\} total=\{scorePerformanceCount\} unassessed=\{unassessedCount\}/)
  assert.match(migration, /'unassessed'/)
  assert.match(students, /Math\.round\(\(activeThisWeek \/ enrollmentsCount\) \* 100\)/)
  assert.match(summary, /label="Precisión global"/)
  assert.match(summary, /Media del alumnado matriculado/)
  assert.match(analytics, /item\.activityCount \/ maxActivityCount/)
  assert.match(analytics, /formatCount\(item\.activityCount, 'respuesta', 'respuestas'\)/)
})

test('attention reasons and grade colours follow the canonical academic semantics', () => {
  const students = read('components/teacher/subject/SubjectStudentsTab.tsx')
  const analytics = read('lib/teacherSubjectAnalytics.ts')
  assert.match(students, /Sin actividad/)
  assert.match(students, /Nota media baja/)
  assert.match(students, /Baja participación/)
  assert.doesNotMatch(students, /actionLabel="Ver todo"/)
  assert.match(analytics, /if \(value >= 9\)/)
  assert.match(analytics, /if \(value >= 7\)/)
  assert.match(analytics, /if \(value >= 5\)/)
})

test('course code actions really copy/share and question management avoids duplicate create actions', () => {
  const utility = read('lib/courseCodeActions.ts')
  const screen = read('app/(teacher)/subject/[id].tsx')
  const questions = read('components/teacher/subject/SubjectQuestionsTab.tsx')
  assert.match(utility, /Clipboard\.setStringAsync/)
  assert.match(utility, /webNavigator\?\.share/)
  assert.match(utility, /Share\.share/)
  assert.match(screen, /detail\.handleShareCode\(\)/)
  assert.match(screen, /detail\.handleCopyCode\(\)/)
  assert.doesNotMatch(questions, /Gestión rápida/)
  assert.doesNotMatch(questions, /Nueva pregunta/)
})

test('duplicate-course modal exposes async loading while the operation is running', () => {
  const modal = read('components/AppModalProvider.tsx')
  const hook = read('features/teacher-subject/useTeacherSubjectDetail.ts')
  assert.match(modal, /onPress\?: \(\) => void \| Promise<void>/)
  assert.match(modal, /await button\.onPress\(\)/)
  assert.match(modal, /loading=\{busyButtonIndex === index\}/)
  assert.match(hook, /\{ label: 'Duplicar', role: 'primary', onPress: handleDuplicate \}/)
})


test('course detail mobile header gives the course identity its own row and keeps the active classroom above every tab', () => {
  const screen = read('app/(teacher)/subject/[id].tsx')
  const header = read('components/ui/RolePageHeader.tsx')
  const structure = read('components/teacher/subject/SubjectCourseStructure.tsx')
  assert.match(screen, /mobileStackedIdentity/)
  assert.match(screen, /compactMobileTitle/)
  assert.match(screen, /mobileSubtitle=\{`\$\{detail\.classrooms\.length\} clase/)
  assert.match(header, /mobileStackedIdentity[\s\S]*backControl[\s\S]*topControls[\s\S]*identity/)
  assert.match(structure, /Clase activa/)
  assert.ok(screen.indexOf('<SubjectClassroomContextSelector') < screen.indexOf('<AppTabs<SubjectTabKey>'))
})

test('mobile tab rails center the active option and communicate overflow with subtle fades', () => {
  const tabs = read('components/ui/AppTabs.tsx')
  assert.match(tabs, /scrollRef\.current\?\.scrollTo\(\{ x: nextOffset, animated: true \}\)/)
  assert.match(tabs, /centeredOffset = layout\.x \+ \(layout\.width \/ 2\) - \(viewportWidth \/ 2\)/)
  assert.match(tabs, /showStartFade/)
  assert.match(tabs, /showEndFade/)
  assert.match(tabs, /<LinearGradient/)
  assert.match(tabs, /mobileRailRow: \{ paddingLeft: 8, paddingRight: 36 \}/)
})

test('question management has one contextual create CTA and a real topic selector', () => {
  const screen = read('app/(teacher)/subject/[id].tsx')
  const questions = read('components/teacher/subject/SubjectQuestionsTab.tsx')
  const structure = read('components/teacher/subject/SubjectCourseStructure.tsx')
  assert.doesNotMatch(screen, /SubjectAddQuestionCTA/)
  assert.doesNotMatch(structure, /SubjectAddQuestionCTA/)
  assert.match(questions, /headerAction=\{<AppButton label="Añadir pregunta"/)
  assert.match(questions, /<AppDropdown<TopicFilter>/)
  assert.match(questions, /label="Tema"/)
  assert.match(questions, /Todos los temas/)
  assert.doesNotMatch(questions, /Gestión rápida/)
})

test('student KPIs are mobile 2x2, selectors are real dropdowns and metrics come from server-wide aggregates', () => {
  const students = read('components/teacher/subject/SubjectStudentsTab.tsx')
  const types = read('lib/teacherServerData.ts')
  const migration = read('supabase/migrations/20260810104500_teacher_course_detail_mobile_hardening.sql')
  const analytics = read('lib/teacherSubjectAnalytics.ts')
  assert.match(students, /flex-row flex-wrap gap-3/)
  assert.match(students, /min-w-\[150px\] flex-1/)
  assert.match(students, /<AppDropdown<StudentStatusFilter>/)
  assert.match(students, /<AppDropdown<StudentSortKey>/)
  assert.doesNotMatch(analytics, /getNextStudentStatusFilter/)
  assert.doesNotMatch(analytics, /getNextStudentSortKey/)
  assert.match(types, /generatedXp: number/)
  assert.match(types, /playedSessionsTotal: number/)
  assert.match(types, /bestStudent: TeacherSubjectStudent \| null/)
  assert.match(types, /attention: TeacherSubjectStudent\[\]/)
  assert.match(migration, /'generatedXp'/)
  assert.match(migration, /'playedSessionsTotal'/)
  assert.match(migration, /'bestStudent'/)
  assert.match(migration, /'attention'/)
})

test('no-activity students stay unassessed and weekly percentages use the same seven-day numerator', () => {
  const migration = read('supabase/migrations/20260810104500_teacher_course_detail_mobile_hardening.sql')
  const students = read('components/teacher/subject/SubjectStudentsTab.tsx')
  const analytics = read('components/teacher/subject/SubjectAnalyticsTab.tsx')
  const summary = read('components/teacher/subject/SubjectSummaryTab.tsx')
  const hook = read('features/teacher-subject/useTeacherSubjectDetail.ts')
  assert.match(migration, /'unassessed'.*not has_activity/s)
  assert.match(migration, /last_activity >= now\(\) - interval '7 days'/)
  assert.match(students, /weeklyActivePercent = enrollmentsCount > 0 \? Math\.round\(\(activeThisWeek \/ enrollmentsCount\) \* 100\)/)
  assert.match(students, /Sin evaluar/)
  assert.match(analytics, /student\.hasActivity \? `\$\{student\.grade\.toFixed\(1\)\}\/10` : 'Sin evaluar'/)
  assert.match(summary, /total=\{overview\.summary\.evaluatedStudents\} unassessed=\{overview\.summary\.unassessedStudents\}/)
  assert.match(hook, /activeTab === 'summary'[\s\S]*overview\.data\.gradeDistribution/)
})

test('student import fails closed for staff accounts and keeps a persistent mobile footer', () => {
  const fn = read('supabase/functions/import-students/index.ts')
  const modal = read('components/teacher/TeacherStudentImportModal.tsx')
  assert.match(fn, /profile\.role_id === 'teacher' \|\| profile\.role_id === 'admin'/)
  assert.match(fn, /cuenta de personal y no puede importarse como alumno/)
  assert.match(fn, /profile\.role_id === 'guest'/)
  assert.match(fn, /rol incompatible con la importación de alumnos/)
  assert.doesNotMatch(fn, /profile\.role_id !== 'student'[\s\S]*role_id: 'student'/)
  const scrollClose = modal.indexOf('</ScrollView>')
  const footer = modal.indexOf('border-t border-border-default bg-surface-raised', scrollClose)
  assert.ok(scrollClose >= 0 && footer > scrollClose)
  assert.match(modal, /label="Cerrar"/)
  assert.match(modal, /label=\{result \? 'Importar otra lista' : 'Importar alumnos'\}/)
})
