import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (path) => readFileSync(join(root, path), 'utf8')

test('course create/edit uses real selectors, current academic years and the exact displayed invite code', () => {
  const form = read('components/teacher/TeacherSubjectForm.tsx')
  assert.match(form, /import AppDropdown/)
  assert.match(form, /<AppDropdown accessibilityLabel=\{label\}/)
  assert.match(form, /FP Básica/)
  assert.match(form, /FP Grado Medio/)
  assert.match(form, /FP Grado Superior/)
  assert.match(form, /\{ value: '', label: 'Sin especificar' \}/)
  assert.match(form, /const startYear = now\.getMonth\(\) >= 8 \? calendarYear : calendarYear - 1/)
  assert.match(form, /p_code: code/)
  assert.match(form, /El código mostrado será exactamente el que se guardará al crear el curso\./)
  assert.doesNotMatch(form, /index \+ 1/)
})

test('course edit preview uses real enrolments and transactional mobile actions protect unsaved changes', () => {
  const form = read('components/teacher/TeacherSubjectForm.tsx')
  assert.match(form, /from\('enrollments'\)\.select\('student_id'\)\.eq\('subject_id'/)
  assert.match(form, /new Set\(enrollmentRows\.map\(\(row\) => row\.student_id\)\)\.size/)
  assert.match(form, /Descartar cambios/)
  assert.match(form, /Hay cambios sin guardar\. Si sales ahora se perderán\./)
  assert.match(form, /addListener\?\.\('beforeRemove'/)
  assert.match(form, /beforeunload/)
  assert.match(form, /absolute bottom-0 left-0 right-0/)
  assert.doesNotMatch(form, /TeacherBottomNav/)
  assert.match(form, /showGlobalSearch=\{false\}/)
  assert.match(form, /title=\{isEdit \? 'Editar curso' : 'Nuevo curso'\}/)
  assert.match(form, /'Crear curso'/)
  assert.doesNotMatch(form, /'Crear Curso'/)
})

test('transactional course and question forms hide the global search', () => {
  const header = read('components/teacher/TeacherPageHeader.tsx')
  const courseForm = read('components/teacher/TeacherSubjectForm.tsx')
  const questionForm = read('components/teacher/TeacherQuestionForm.tsx')
  assert.match(header, /showGlobalSearch\?: boolean/)
  assert.match(header, /showGlobalSearch = true/)
  assert.match(courseForm, /showGlobalSearch=\{false\}/)
  assert.match(questionForm, /showGlobalSearch=\{false\}/)
})

test('course detail keeps a persistent class context across all tabs and URLs', () => {
  const screen = read('app/(teacher)/subject/[id].tsx')
  const structure = read('components/teacher/subject/SubjectCourseStructure.tsx')
  const hook = read('features/teacher-subject/useTeacherSubjectDetail.ts')
  const selectorIndex = screen.indexOf('<SubjectClassroomContextSelector')
  const tabsIndex = screen.indexOf('<AppTabs<SubjectTabKey>')
  assert.ok(selectorIndex >= 0 && tabsIndex > selectorIndex)
  assert.match(structure, /export function SubjectClassroomContextSelector/)
  assert.match(structure, /Este contexto se mantiene al cambiar entre Resumen, Temas, Preguntas, Alumnos y Analítica\./)
  assert.match(hook, /router\.setParams\(\{ classroomId: String\(nextClassroomId\) \}/)
  assert.match(screen, /classroomId=\$\{classroomId\}/)
})

test('course analytics uses one metric definition, evaluated-only grade bands and real weekly activity', () => {
  const migration = read('supabase/migrations/20260809193000_teacher_course_detail_consistency.sql')
  const students = read('components/teacher/subject/SubjectStudentsTab.tsx')
  const analytics = read('components/teacher/subject/SubjectAnalyticsTab.tsx')
  const summary = read('components/teacher/subject/SubjectSummaryTab.tsx')
  assert.match(migration, /'activeThisWeek'.*interval '7 days'/s)
  assert.match(migration, /100\.0 \* sum\(correct_answers\) \/ sum\(total_answers\)/)
  assert.match(migration, /from rows where total_answers > 0 and grade >= 9/)
  assert.match(migration, /Notable \(7-8\.9\)/)
  assert.match(migration, /Aprobado \(5-6\.9\)/)
  assert.match(migration, /Suspenso \(<5\)/)
  assert.doesNotMatch(migration, /Bueno \(/)
  assert.doesNotMatch(migration, /Regular \(/)
  assert.match(students, /GradeDistributionBars distribution=\{gradeDistribution\} total=\{scorePerformanceCount\}/)
  assert.match(students, /Math\.round\(\(activeThisWeek \/ enrollmentsCount\) \* 100\)/)
  assert.match(summary, /label="Precisión global"/)
  assert.match(summary, /Media del alumnado matriculado/)
  assert.match(analytics, /item\.activityCount \/ maxActivityCount/)
  assert.match(analytics, /formatCount\(item\.activityCount, 'respuesta', 'respuestas'\)/)
})

test('attention reasons and grade colours follow the canonical academic semantics', () => {
  const students = read('components/teacher/subject/SubjectStudentsTab.tsx')
  const analytics = read('lib/teacherSubjectAnalytics.ts')
  assert.match(students, /Sin actividad/)
  assert.match(students, /Nota media baja/)
  assert.match(students, /Baja participación/)
  assert.doesNotMatch(students, /actionLabel="Ver todo"/)
  assert.match(analytics, /if \(value >= 9\)/)
  assert.match(analytics, /if \(value >= 7\)/)
  assert.match(analytics, /if \(value >= 5\)/)
})

test('course code actions really copy/share and question management avoids duplicate create actions', () => {
  const utility = read('lib/courseCodeActions.ts')
  const screen = read('app/(teacher)/subject/[id].tsx')
  const questions = read('components/teacher/subject/SubjectQuestionsTab.tsx')
  assert.match(utility, /Clipboard\.setStringAsync/)
  assert.match(utility, /webNavigator\?\.share/)
  assert.match(utility, /Share\.share/)
  assert.match(screen, /detail\.handleShareCode\(\)/)
  assert.match(screen, /detail\.handleCopyCode\(\)/)
  assert.doesNotMatch(questions, /Gestión rápida/)
  assert.doesNotMatch(questions, /Nueva pregunta/)
})

test('duplicate-course modal exposes async loading while the operation is running', () => {
  const modal = read('components/AppModalProvider.tsx')
  const hook = read('features/teacher-subject/useTeacherSubjectDetail.ts')
  assert.match(modal, /onPress\?: \(\) => void \| Promise<void>/)
  assert.match(modal, /await button\.onPress\(\)/)
  assert.match(modal, /loading=\{busyButtonIndex === index\}/)
  assert.match(hook, /\{ label: 'Duplicar', role: 'primary', onPress: handleDuplicate \}/)
})
